### ISSUE TITLE
installing python modules using pip

### ISSUE THREAD

**Issue by alih1958** [proevo/pythondotorg#1868]
whenever I try to install a module or program using " pip install       " I get the following respond
"  Defaulting to user installation because normal site-packages is not writeable"
so how I can solve this

**Comment by git-lijo** [comment]
Please check if you have multiple versions of Python installed. 
Try reinstalling or updating the python versions

**Comment by lucifertrj** [comment]
https://docs.python.org/3/installing/index.html?highlight=pip#work-with-multiple-versions-of-python-installed-in-parallel
Check this link, I guess it will solve the problem

**Comment by profMsaif** [comment]
it is more likely that you install python with sudo privilege to a directory that requires sudo to be accessed, hence
"site-packages is not writable"
site-packages is the directory where python install the packages with pip.
you can use sudo pip install but it is better not to do that.
you shoud check the permission of the directory site-packages  to make sure.

**Comment by ned-deily** [comment]
Thanks for the report but this issue tracker is for issues with the python.org website rather than for issues with Python use or installation. You would likely have received faster and more complete help using one of the resources on the [python.org help page](https://www.python.org/about/help/).
