### ISSUE TITLE
Back to Top

### ISSUE THREAD

**Issue by rofhiwaarnoldsemase** [proevo/pythondotorg#1870]
Back to Top doesn't work on your website.

![Screenshot_20210921-215615](https://user-images.githubusercontent.com/72657173/134239375-0e265bc4-411f-419e-b1a3-8da8c3c8f41c.jpg)

**Comment by kailash360** [comment]
Can I work on this issue?

**Comment by rofhiwaarnoldsemase** [comment]
Yes, You can work on the issue.
