### ISSUE TITLE
Setup Failed Python Download

### ISSUE THREAD

**Issue by KingArthamus** [proevo/pythondotorg#1871]
Please help or I'm totally gonna fail my intro to programming course! When I go to Python.org/downloads and I download the newest version 3.9.7 When I try installing it gives me a setup failed error. It says  One or more issues caused the setup to fail. Please fix issues and then retry set up. For more information see the log file. 0x80070642 user cancelled installation

I'm not cancelling anything It tries loading the install and just gives me the above error message seconds later.

Below is a link to the log file

[Python 3.9.7 (64-bit)_20210921211706.log](https://github.com/python/pythondotorg/files/7210254/Python.3.9.7.64-bit._20210921211706.log)
n

**Comment by Pranavteja123** [comment]
Thanks for your question

 

There are a couple of reasons why you might receive that error code of User Cancelled Installation. Assuming you aren’t pressing the cancel button during the installation then the next step would be to ensure that you are running the installer with full Windows Administrator permissions.

 

Additionally, one thing that has assisted some users is to ensure that all previous versions of AccountRight and the API are uninstalled on that computer for all users before trying the install again.

 

Do let us know how you get on with this

Regards,
Pranav

**Comment by Kpravi1311** [comment]
I was able to resolve the error by unchecking the 'Install launcher for all users. Once unchecked, the installer worked as expected without any issue



![git hub sol](https://user-images.githubusercontent.com/95520693/144701297-b97586dd-0c32-42ea-9ec8-dddd7dfd7c48.png)

Presumably, there was an issue with folder permissions since this was on a managed work machine.

Do let us know how you get on with this

Regards,
Pravallika

**Comment by ned-deily** [comment]
Thanks for the report but this issue tracker is for issues with the python.org website rather than for issues with Python use or installation. You would likely have received faster and more complete help using one of the resources on the [python.org help page](https://www.python.org/about/help/).
