### ISSUE TITLE
missing Supporting Member 

### ISSUE THREAD

**Issue by bahadiraraz** [proevo/pythondotorg#1874]
**Describe the bug**
The 276th person does not appear on the donations page

**To Reproduce**
1. Go to https://www.python.org/psf/donations/
3. Scroll down to 'the 276th person
4. See an error

**Expected behavior**
276. person's name is not displayed when it should be

**Screenshots**
![image](https://user-images.githubusercontent.com/48323786/134484621-e8a11465-be31-4fe9-ada4-cc01d60dd87d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [chrome]

**Comment by girolamodaschio** [comment]
I think this issue must be closed.

![image](https://user-images.githubusercontent.com/58935223/147108855-0088d890-bdb6-422b-aa03-f283eaff65bb.png)
