### ISSUE TITLE
<link rel="canonical"> in 3.11 docs points at docs.python.org/3/ which is older

### ISSUE THREAD

**Issue by ambv** [proevo/pythondotorg#1880]
Example:
https://docs.python.org/3.11/whatsnew/3.11.html

In HTML source, you'll find:
```html
<link rel="canonical" href="https://docs.python.org/3/whatsnew/3.11.html" />
```

This is a bad canonical link (404) since /3/ at the moment points at 3.9 (and very soon will point at 3.10) where there is no "What's New in Python 3.11" page. This is a problem because search engines and social networking link scrapers redirect to canonical links by default.

We should be smarter about this so that *newer* documentation editions than the default /3/ should simply skip the canonical link altogether. This is the simplest thing we can do that will ensure that:
- there is no 404 redirect
- nothing breaks when that version becomes the default and we start redirecting it to /3/

**Comment by ned-deily** [comment]
@JulienPalard, ideas?

**Comment by JulienPalard** [comment]
docsbuild scripts knows which version is pointed to by `/3/` so it knows which version should not have the canonical link.

But I think we should keep canonical links from `/anything_newer_than_slash_3/` to `/3/` when the page exist to avoid crawlers to see duplicate content.

Maybe docsbuild script can be smart enough to remove canonicals to non-existing pages.

**Comment by JulienPalard** [comment]
Fixed in https://github.com/python/docsbuild-scripts/commit/40ce6d110914b1b929db9f7655898aaf105624b8.

**Comment by hugovk** [comment]
Confirmed that:

* https://docs.python.org/3.11/whatsnew/3.11.html has no canonical link
* https://docs.python.org/3.11/whatsnew/3.10.html does:
```html
<link rel="canonical" href="https://docs.python.org/3/whatsnew/3.10.html" />
```

Can we close this issue? (I would but triagers don't have close permission for this repo.)

**Comment by Mariatta** [comment]
Thanks everyone.
