### ISSUE TITLE
RE: Python 3.10.0 Something completely different

### ISSUE THREAD

**Issue by jhilton00** [proevo/pythondotorg#1888]
Regarding "And now for something completely different" on www.python.org/downloads/release/python-3100

First 'propper' isn't proper.
Second, would you mind adding something like...
"Ponder this: If a mirror is dropped into the Schwarzschild black hole and a laser is pointed at it while it falls towards the event horizon, when does the reflection stop? The answer is surprising! A 1 minute proper time fall is not 1 minute to the observer."

**Comment by ned-deily** [comment]
Thanks for the report. The typo has been fixed.
