### ISSUE TITLE
community-landing/diversity page unavailable

### ISSUE THREAD

**Issue by atarax665** [proevo/pythondotorg#1905]
**Describe the bug**
The [community-landing/diversity](https://www.python.org/community-landing/diversity) page is unavailable.
When I clicked on the Diversity Statement word on the community-landing page then  I was redirected [here](https://www.python.org/community-landing/diversity). 

**To Reproduce**
1. Go to https://www.python.org/community-landing/
2. Scroll down to Diversity Statement
3. Click on that.
4. You will be redirected to https://www.python.org/community-landing/diversity

**Expected behavior**
The hyperlink on `Diversity Statement` word in the landing page should be replaced by https://www.python.org/community/diversity/ to resolve this issue.

**Screenshots**
![Python](https://user-images.githubusercontent.com/29673671/139570713-68bceb6c-4f06-45dc-9c36-b009cbe136e7.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version 95.0.4638.69

**Comment by kinow** [comment]
Same here. I had never accessed the diversity page, so went to python.org, and clicked on the top-most link for community, then diversity, and 404. Other links to the diversity page appear to be OK. Couldn't locate the source for that file in this repo, otherwise would have prepared a PR. Thanks.

**Comment by ned-deily** [comment]
Thanks for the report. The link to the diversity page is now fixed, it should have been https://www.python.org/community/diversity/.
