### ISSUE TITLE
Dlib error

### ISSUE THREAD

**Issue by ashishm46** [proevo/pythondotorg#1906]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ashishm46** [comment]
in python 3.9 dlib is not working

**Comment by stevendaprano** [comment]
Hi ashishm46 ,

This is an issue tracker for bugs on the Python.org website, not a help desk for asking for help with Python programming issues.

In the future, please ask these sorts of questions on the many different forums which are intended for asking for help. Go to the Python.org website and click on the Community menu to see various forums, mailing lists and IRC channels were you can ask for help. Or you can try Reddit's r/learnpython.

You will need to provide more detail than just "is not working".

To get help with dlib, you may need to contact the dlib maintainers and ask them. See their page on PyPI.
