### ISSUE TITLE
dead link on https://www.python.org/doc/av/

### ISSUE THREAD

**Issue by mwichmann** [proevo/pythondotorg#1912]
Mail sent to webmaster@python.org reported a broken link.

Go to: https://www.python.org/doc/av/
scroll down to **Inactive video series**.
the links to 5 Minutes with Python don't work.

Clearly there's recognition those aren't current, but the other resources under "Inactive" tags do actually still resolve to something.

**Comment by 0623260029** [comment]
Very good

**Comment by attreyee-muk** [comment]
I want to try solving this issue. Can you please guide me on the same?

**Comment by ned-deily** [comment]
Thanks for the report. That web page was deactivated a few years ago as a result of #1442 but we overlooked this reference. Now removed.
