### ISSUE TITLE
PEP 596 needs an update

### ISSUE THREAD

**Issue by yairp03** [proevo/pythondotorg#1913]
**The bug**
PEP 596 needs an update.

**Steps to reproduce the behavior:**
1. Go to [PEP 596](https://www.python.org/dev/peps/pep-0596/)
2. Scroll down to 'Release Schedule - Bugfix releases'
3. See that "3.9.8: Monday, 2021-11-01" is in the 'Expected' section when it should be in the 'Actual' section.

![gFK5nNt](https://user-images.githubusercontent.com/45571379/141142435-4a757a0d-1639-47dc-ab92-e2c4784fc769.png)

**Desktop**
 - OS: Windows
 - Browser: chrome
 - Version: 95

**Comment by ned-deily** [comment]
Thanks for the report. The schedule in the PEP has subsequently been updated and currently reflects the most recent releases.
