### ISSUE TITLE
[Suggestion] Add Thumbs-up Function on bugs.python.org to rank issues

### ISSUE THREAD

**Issue by BurgessX** [proevo/pythondotorg#1919]
**Is your feature request related to a problem? Please describe.**
Yes. I found that some CPython issues that really matter, like [issue 41929](https://bugs.python.org/issue41929
), are not solved for years. They may be deadly bugs. If these important and urgent issues can be noticed more easily, it will be helpful.

**Describe the solution you'd like**
For the above reason, I suggest that you develop a **Like** or **Thumb Up** function to rank all of the issues so that developers can choose to deal with the urgent issues by sorting by the number of Likes. This function can be like such of StackOverflow.

**Additional context**
It can be like this:
![image](https://user-images.githubusercontent.com/52914833/141798278-89da734b-5d71-48d3-980d-894b0a3949f4.png)

**Comment by Mariatta** [comment]
Thanks for the suggestion. We are actually in the process of migrating our bug tracker from b.p.o into GitHub Issues per [PEP 581](https://www.python.org/dev/peps/pep-0581/) and [PEP 588](https://www.python.org/dev/peps/pep-0588/). Once we're on GitHub issues you will be able to vote by giving the thumbs-up reaction.
