### ISSUE TITLE
TypeError: As of 3.10, the *loop* parameter was removed from Condition() since it is no longer necessar

### ISSUE THREAD

**Issue by AttaULSaboor** [proevo/pythondotorg#1922]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. It would be great if [...]
I am trying to connect FastAPI to MariaDB but I got This Error which one I mentioned below:
TypeError: As of 3.10, the *loop* parameter was removed from Condition() since it is no longer necessary

**Describe alternatives you've considered**

**Additional context**

**Comment by AttaULSaboor** [comment]
How can I fix this error please guide me I will really appreciate you. Thank You.

TypeError: As of 3.10, the *loop* parameter was removed from Condition() since it is no longer necessary

**Comment by Pranavteja123** [comment]
(or alternatively they can cache the running `loop`, but the first loop lookup should be performed with `asyncio.get_running_loop()`)

for details click here:- https://bugs.python.org/issue42392

**Comment by stevendaprano** [comment]
Hi AttaULSaboor,

This is an issue tracker for bugs on the Python.org website, not a help desk to ask questions about Python.

In the future, please ask these sorts of questions on the many different forums which are intended for asking for help. Go to the Python.org website and click on the Community menu to see various forums, mailing lists and IRC channels were you can ask for help. Or you can try Reddit's r/learnpython.
