### ISSUE TITLE
Website Typo

### ISSUE THREAD

**Issue by john9631** [proevo/pythondotorg#1924]
Latest Release: https://www.python.org/downloads/release/python-3100/

In And now for something completely different

`maximum propper time`  should be `maximum proper time`

**Comment by 9tliea** [comment]
nice

**Comment by attreyee-muk** [comment]
Hello! Can you please guide me with the file I need to see for fixing this issue? I'm new to this organisation and want to contribute.

**Comment by ned-deily** [comment]
Thanks for the report! Now fixed.
