### ISSUE TITLE
1.3 - 1 produces 0.30000000000000004

### ISSUE THREAD

**Issue by justintim-es** [proevo/pythondotorg#1927]
How to get 0.3 without rounding?

**Comment by ghost** [comment]
This should do it:
`round(1.3-1, 1)`

**Comment by mehmet-mert** [comment]
Try "fractions" module.

**Comment by stevendaprano** [comment]
Hi noahsalvadordenjo,

This is a bug tracker for bugs on the Python website, not a help desk to ask questions about Python.

In the future, please ask these sorts of questions on the many different forums which are intended for asking for help. Go to the Python.org website and click on the Community menu to see various forums, mailing lists and IRC channels were you can ask for help. Or you can try Reddit's r/learnpython.

In the meantime, I'll just point you to the FAQ about this sort of issue:

https://docs.python.org/3/faq/design.html#why-are-floating-point-calculations-so-inaccurate
