### ISSUE TITLE
Missing key kwarg in bisect.bisect doc

### ISSUE THREAD

**Issue by Sebolains** [proevo/pythondotorg#1929]
**Describe the bug**
Python 3.10 added the optional keyword argument `key` to the `bisect.bisect` function. While the documentation for this function describes this argument, it is not present in the function definition.

**To Reproduce**
See https://docs.python.org/3/library/bisect.html#bisect.bisect

**Expected behavior**
The `key` argument is added to the `bisect.bisect` function definition in the documentation page, similar to `bisect.bisect_right`.

**Comment by Mariatta** [comment]
Thanks for the report, but this is not the right issue tracker for it.

Can you please file it in https://bugs.python.org?


Thanks.
