### ISSUE TITLE
Remove reference to Ewa in the Get Involved page once she leaves at the end of 2021

### ISSUE THREAD

**Issue by stevendaprano** [proevo/pythondotorg#1943]
On page:

https://www.python.org/psf/get-involved/

it says "Know of a company that should sponsor the PSF? Tell me or link them to our sponsor page." and the word "me" is a link to Ewa's email address.

Ewa is leaving the PSF at the end of this year (2021) so that will need to changed when she does.

**Comment by cacoze** [comment]
It seems this one was already solved. 
![image](https://user-images.githubusercontent.com/1657123/209862759-ab600b92-485b-4b12-9d46-f6dbeb63eb7f.png)

**Comment by Mariatta** [comment]
Thanks for confirming that the page has been updated.
