### ISSUE TITLE
Mailing Lists page refers to python-porting, which no longer exists

### ISSUE THREAD

**Issue by ericvsmith** [proevo/pythondotorg#1958]
**Describe the bug**
The python-porting mailing list is referenced, but it no longer exists.

**To Reproduce**
1. Go to https://www.python.org/community/lists/ 
2. Search for "Porting mailing list"
3. Click on the link in that section
4. The resulting page doesn't show information on python-porting, and says "No such list python-porting".

**Expected behavior**
The python-porting list should no longer be referenced from anywhere.

**Comment by ned-deily** [comment]
Removed, thanks!
