### ISSUE TITLE
ImportError: cannot import name 'dataclass'

### ISSUE THREAD

**Issue by leonekwolfik** [proevo/pythondotorg#1963]
**Describe the bug**
When try run code with import data classes I get error:
1:
```
Traceback (most recent call last):
  File "/Users/b/PycharmProjects/pythonProject/dataclasses.py", line 1, in <module>
    from dataclasses import dataclass
  File "/Users/b/PycharmProjects/pythonProject/dataclasses.py", line 1, in <module>
    from dataclasses import dataclass
ImportError: cannot import name 'dataclass' from partially initialized module 'dataclasses' (most likely due to a circular import) (/Users/bartek/PycharmProjects/pythonProject/dataclasses.py)
```
or
2:
```
Traceback (most recent call last):
  File "/Users/b/PycharmProjects/pythonProject/dataclasses.py", line 1, in <module>
    import dataclasses as dc
  File "/Users/b/PycharmProjects/pythonProject/dataclasses.py", line 3, in <module>
    @dataclasses.dataclass
AttributeError: partially initialized module 'dataclasses' has no attribute 'dataclass' (most likely due to a circular import)

```

I get it with Python 3.9 and 3.10.

**To Reproduce**
Code to reproduce:
1:  `from dataclasses import dataclass`
2:  `import dataclasses`

**Expected behavior**
Import dataclasses

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Python: 
   '3.9.9 (v3.9.9:ccb0e6a345, Nov 15 2021, 13:06:05) \n[Clang 13.0.0 (clang-1300.0.29.3)]'
   '3.10.1 (v3.10.1:2cd268a3a9, Dec  6 2021, 14:28:59) [Clang 13.0.0 (clang-1300.0.29.3)]'

**Comment by ned-deily** [comment]
This issue tracker is for issues regarding the python.org website not for the Python language or implementations.  That said, it looks like you have named one of your files the same as one of the Python standard library modules, `dataclasses`.  Don't do that!

https://www.python.org/about/help/
https://docs.python.org/3/library/dataclasses.html

**Comment by KiranQureshi53** [comment]
@leonekwolfik please rename your python file name and try again. Chances are your code is getting confused between the module name and file name. Thanks

**Comment by nitish9413** [comment]
I am facing this issue
`Import "dataclasses.dataclass" could not be resolved Pylance[reportMissingImports]`
in vs code

tried to install dataclass again but does not work

file name = "config_entity.py"
