### ISSUE TITLE
Staging server shows up in search results

### ISSUE THREAD

**Issue by PetteriAimonen** [proevo/pythondotorg#1980]
**Describe the bug**
[https://staging.python.org/downloads/windows/](https://staging.python.org/downloads/windows/) shows up quite high in Bing search results, but contains outdated material.

**To Reproduce**
1. On Windows and Edge browser, search for "python download".
2. Blindly click on the first `python.org` link you happen to notice.
3. Proceed to download Python 3.4.

**Expected behavior**
Staging server could be hidden from search results, with `robots.txt` or similar.

**Comment by hugovk** [comment]
I no longer see any results for `staging.python.org` and I get "This site can’t be reached" for https://staging.python.org/ itself.

@PetteriAimonen Thanks for the report, please can you close this if it's no longer a problem for you?

**Comment by PetteriAimonen** [comment]
Thanks!
