### ISSUE TITLE
This image not being found as "/static/metro-icon-144x144-precomposed.png"

### ISSUE THREAD

**Issue by xinghuo4096** [proevo/pythondotorg#1988]
**Describe the bug**

Resulting in this image not being found as** "/static/metro-icon-144x144-precomposed.png" **when using windows 10 for the homepage.
The correct image name should be **"metro-icon-144x144.png"**

**Desktop (please complete the following information):**

 - OS: windows11
 - Browser ：edge，firefox

** other **

` pythondotorg/templates/base.html `
```
    {# Tile icon for Win8 (144x144 + tile color) #}
    <meta name="msapplication-TileImage" content="{{ STATIC_URL }}metro-icon-144x144-precomposed.png"><!-- white shape -->
```

**Comment by ddevdan** [comment]
Can you check if it works please? @xinghuo4096
