### ISSUE TITLE
Button out of order. (Back to top button) not working

### ISSUE THREAD

**Issue by Robocoder15** [proevo/pythondotorg#1992]
@
![Screenshot_20220219-141008_Chrome](https://user-images.githubusercontent.com/100018869/154793685-10a17a8a-5618-4ec0-9032-483db25340f2.jpg)

This button is not working

**Comment by hugovk** [comment]
Thanks for the report, let's close as a duplicate of https://github.com/python/pythondotorg/issues/1278.
