### ISSUE TITLE
iFrame is not responsive

### ISSUE THREAD

**Issue by marvinhuelsmann** [proevo/pythondotorg#2004]
**Bug description**
At the community-landing site is a Youtube iFrame which is not responsive.

**Reproduce**
1. Go to 'https://www.python.org/community-landing/'
2. Switch to the responsive view
4. See the iFrame

**Screenshot**
![image](https://user-images.githubusercontent.com/59929827/156902537-1360dabf-113d-4496-a608-3e9b0619d56c.png)

**Comment by mbiesiad** [comment]
I confirm, it still occurs. (2022-5-27)

Normal (correct view):
![image](https://user-images.githubusercontent.com/18367606/170776337-96310cf3-5704-4fea-bab5-2aed48c82e16.png)

Issue:
![image](https://user-images.githubusercontent.com/18367606/170776413-a71f4a97-d821-4d03-be05-8e0effb98614.png)

Example:
797px x 457px

// Browser: Chrome, as well as Firefox for instance.
Best wishes,

**Comment by karlafalcao** [comment]
Maybe it doesn't make sense anymore as the new site version -> (https://staging.python.org) got totally rid of this page.

**Comment by marvinhuelsmann** [comment]
👍
