### ISSUE TITLE
python takes long time when return big data

### ISSUE THREAD

**Issue by HuDi2018** [proevo/pythondotorg#2008]
**Describe the bug**
it takes a long time when python return big data.
generally, when a function return something, it only take less than 1e-5 second, 
but when the result is big, like np.random.rand(2048,3,224,224), the time cost will increase to 0.1-0.2 second

**To Reproduce**
```
import numpy as np
import time


currentT = None


def myfunc():
    global currentT
    arr1 = np.random.rand(2040, 3, 224, 224)
    arr2 = np.random.rand(2040, 3, 224, 224)
    currentT = time.time()
    return (arr1,arr2)


totalT = 0
for i in range(50):
    result = myfunc()
    deltaT = time.time()-currentT
    print('delatT',deltaT)
    totalT += deltaT

print('myfunc()', totalT)
```

**Expected behavior**
the first deltaT printed is 1e-5, which seems normally, but after the time increases to 0.2 second

**Screenshots**
![image](https://user-images.githubusercontent.com/40233154/157628785-d5548687-a7c1-471a-a136-6e51872ced32.png)

**Comment by AlexWaygood** [comment]
This issue tracker is for bugs relating to the Python.org website itself, not for bugs in Python code. You should probably post your question in the "Users" section of https://discuss.python.org/,  StackOverflow, or a numpy issue tracker.

**Comment by Mariatta** [comment]
This issue tracker is not the right place to ask such question. Please try the above resources mentioned by Alex.
