### ISSUE TITLE
Cant find Python docker images

### ISSUE THREAD

**Issue by MaxwellDupre** [proevo/pythondotorg#2010]
**Description**
I want to download the latest Python docker images and clicking on the [link](https://quay.io/repository/python-devs/ci-image) takes me to a page that says repository not found.
![Screenshot from 2022-03-15 18-46-59](https://user-images.githubusercontent.com/14096356/158450735-8d4f9730-8e3a-45d8-93e6-b37625fc1e7f.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [Python download page](https://www.python.org/downloads/)
2. Click on [Docker Images](https://quay.io/repository/python-devs/ci-image)
3. After logging in to RH (why BTW, never needed to do this before?)
4. See error above

**Expected behaviour**
A page with a list of Python docker images for different versions

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Ubtunu
 - Browser brave
 - Version [Version 1.36.112 Chromium: 99.0.4844.51 (Official Build) (64-bit)](https://brave.com/latest/)

**Smartphone (please complete the following information):**

**Comment by Mariatta** [comment]
Huh.. I'm also wondering why the url is pointing to the RedHat website.

I would think it should go to https://hub.docker.com/_/python

**Comment by Harry-Hopkinson** [comment]
I can fix this

**Comment by merwok** [comment]
The Python images on Docker Hub are maintained by Docker, not PSF or python-dev, so there is no quality control and no official (python official) endorsement of them.

The CI images on Quay.io are maintained by python-dev (@warsaw IIRC).  I don’t remember if these were meant for use by some python-dev projects or meant for general usage by developers using Python.

**Comment by warsaw** [comment]
Those [CI images](https://gitlab.com/python-devs/ci-images/-/tree/main) are no longer hosted on Quay, they are hosted in GitLab's [container registry](https://gitlab.com/python-devs/ci-images/container_registry/48153).  They are mostly kept up-to-date automatically (the README still requires [manual updates](https://gitlab.com/python-devs/ci-images/-/issues/14)).

@maxking and I maintain this repository, but I think we'd both be happy to have collaborators.

**Comment by warsaw** [comment]
> After logging in to RH (why BTW, never needed to do this before?)

No login should be needed to use the GL registry.

> Click on [Docker Images](https://quay.io/repository/python-devs/ci-image)

Could someone with access to the Python download page please update this URL?

**Comment by ambv** [comment]
Fixed.
