### ISSUE TITLE
Python No Module Named PIP

### ISSUE THREAD

**Issue by devashish2024** [proevo/pythondotorg#2011]
I was installing ursina python package using `pip install ursina`. It success, then at last It said 'You're using pip version (VERSION, idk); however, (VERSION,IDK) is available. Run pip install --upgrade pip to update.

I did try to upgrade, next it failed as it is saying to also use the `--user` argument. I tried it next, but it next say me that pip is not installed:
```
Microsoft Windows [Version 10.0.22000.556]
(c) Microsoft Corporation. All rights reserved.

C:\Users\codew>pip
Traceback (most recent call last):
  File "E:\Programs\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Programs\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Programs\Python\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'

C:\Users\codew>
```
HELP

**Comment by AlexWaygood** [comment]
Please post your question at https://discuss.python.org/c/users/7 or on Stackoverflow.com. This issue tracker is for issues relating to the python.org website itself, not general bugs or problems relating to Python.

**Comment by Mariatta** [comment]
The issue tracker is for python.org website, not for general questions on how to use Python. Please try the resources mentioned by Alex above.

**Comment by devashish2024** [comment]
Ok
