### ISSUE TITLE
Mac OSX 12.3 Monterey - Python3 Tkinter produces black screens

### ISSUE THREAD

**Issue by donniebergh** [proevo/pythondotorg#2014]
**HELP!**

I've tried just about all of the Google fixes and still all tk windows/dialogs have a black screen background! I have even tried the Brew installs without any luck ("brew install python-tk@3.10", "brew install python-tk").

**Background**
I recently updated my MacBook Pro OS to Monterey 12.3 - A clean install from scratch. Now all of my Python/Tkinter apps (I've developed) have a black background hiding the text, buttons etc. The apps appear to still work if get a lucky click on a button.

I'm in the process of learning Python and this has thrown a wrench into the works! I hope there is a simple explanation and fix.

Please provide me with help you can.

Thank you,
-Donnie

**Code:**
from tkinter import *

app = Tk()

app.title('My App')
app.geometry('500x300')
app.configure(background='white')

app.mainloop()

<img width="593" alt="BlackScreen" src="https://user-images.githubusercontent.com/52159256/160248388-0e7a1ec1-1adb-422e-b556-114f74d4c8b6.png">

<img width="593" alt="Terminal" src="https://user-images.githubusercontent.com/52159256/160248463-5ff35392-d3ed-4e90-a8c3-51d482a662d4.png">

**Comment by marksweb** [comment]
This issue tracker is for bugs relating to the python.org website itself, not for bugs in Python code. You should probably post your question in the "Users" section of https://discuss.python.org/ or stackoverflow.
