### ISSUE TITLE
Back to Top button not working on mobile

### ISSUE THREAD

**Issue by theranjitraut** [proevo/pythondotorg#2026]
**Describe the bug**
Back to Top button is not working on mobile

**To Reproduce**
1. Go to python.org using mobile and chrome browser
2. Scroll down to the bottom
3. Click on 'Back to Top' button
4. The button is not working

**Expected behavior**
Cannot scroll to the top from the bottom of the page

**Screenshots**
![Python Bug](https://user-images.githubusercontent.com/67329253/162552109-a1c73148-d762-47fc-b16a-870b47382f6e.jpg)

https://user-images.githubusercontent.com/67329253/162552148-7cc8fbf8-0602-49d8-b14a-55b005066aa1.mp4

**Smartphone**
 - Device: [Redmi Y3]
 - OS: [Andriod 10]
 - Browser [Chrome]
 - Version [98.0.4758.87]

**Comment by alvindera97** [comment]
Just confirmed this bug too. 

**Smartphone**
• Device: [Redmi 10]
• OS: [Android 11]
• Browser: [Chrome]
• Version: [99.0.4844.88]
