### ISSUE TITLE
link [enovad] in success stories leads to pornographic website 

### ISSUE THREAD

**Issue by amrajat** [proevo/pythondotorg#2029]
https://www.python.org/success-stories/python-to-deliver-commercial-anti-spam-software/
The above link contains this code `<a class=" reference external" href="http://www.enovad.com/">Enovad</a>` which leads to a porn site, maybe it was hacked while I visited that site. Please take appropriate action.

**Comment by amrajat** [comment]
![python-bug](https://user-images.githubusercontent.com/26631696/162796166-82edf9ab-9600-4782-9e31-8664553cd7fe.png)

**Comment by joncle** [comment]
I've marked this an "unpublished" until someone can take a better look at it.

**Comment by ppo** [comment]
Same problem on [Creating And Distributing Your Own Screencasts](https://www.python.org/doc/av/howto/).

In the first paragraph: _The [ShowMeDo](http://www.showmedo.com/) site offers a collection of screencasts that [teach you how to produce your own screencasts](http://showmedo.com/videos/screencasting)._

Both links show the same content with links to a porn site.

**Comment by JacobCoffee** [comment]
Removed, has been unpublished for a long time and most of the links are broken anyways.
