### ISSUE TITLE
Bookmark button "Back to Top" is not working

### ISSUE THREAD

**Issue by hslee2008** [proevo/pythondotorg#2038]
# Describe the bug
In index file, the first and second "Back to Top" button is not working.
It changes the background color when I click it but nothing changes other than that.

# More Description
I tried adding the exact same code of the bookmark right after the one that is not working.
It seems like the first button is the one that is not working.
Maybe there is a problem with the CSS code.

# To Reproduce
1. Go to 'https://www.python.org'
2. Scroll to the bottom and find 'Back to Top' button
3. Click on the button
4. See background color changing
5. Nothing happens

# Expected Behavior
In step 5, the bookmark should bring the users to the top of the page.

# Devices/Browser
All major browsers in both computer and phone.

**Comment by hslee2008** [comment]
```js
/* ! Not currently working in IE10/Windows 8, Chrome for Android, Firefox (all versions)... something about the animate() function */
$("#close-python-network").click(function() {
  $('body, html').animate({ scrollTop: $('#python-network').offset().top }, 300);
  return false;
});

$("#python-network").click(function() {
  $('body, html').animate({ scrollTop: $('#top').offset().top }, 300);
  return false;
});

$("#back-to-top-1, #back-to-top-2").click(function() {
  $("body").animate({ scrollTop: $('#python-network').offset().top }, 500);
  return false;
});
```

Have seen the code in pythondotorg/static/js/script.js file.
Not sure about the comment.
Very vague and hard for contributors & out side people to understand.
If the `animate()` is not working, please explain in more detail why it isn't.

**Comment by Atik-Mujawar** [comment]
I am interested to contribute.
