### ISSUE TITLE
Job description partially appearing above the top menu

### ISSUE THREAD

**Issue by kinow** [proevo/pythondotorg#2046]
**Describe the bug**

Hi, there's a [job](https://www.python.org/jobs/6504/ that's causing the HTML produced by Django/libs to show part of the job description above the top menu, as per screenshot below.

![image](https://user-images.githubusercontent.com/304786/168458634-f93b88cd-2ac5-46af-a2b1-a031da2fde86.png)

I disabled NoScript and the issue wasn't fixed. I couldn't see the same error when browsing other jobs. So I suspect there's some text in that specific job description that's not well escaped.

**To Reproduce**
1. Go to <https://www.python.org/jobs/6504/>
2. See error on the menu

**Expected behavior**

No error :)

**Screenshots**

Above

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu LTS
 - Browser Firefox
 - Version 100 (same problem on chromium)

**Additional context**

Was going to send a PR, but realized it could be an issue hard to reproduce without knowing exactly how the data looks like on the server side (i.e. not having access to the jobs data).

Thanks
-Bruno

**Comment by BharathSatheeshKumar** [comment]
Better try to remove the string ,save and run it, if it has any glitches then its just the M-Firefox fault, if it doesn't then go ahead and put back the string. The page will be alright

**Comment by joncle** [comment]
Related #2020

**Comment by aisk** [comment]
The link in the first comment is 404 now, there is another sample: https://www.python.org/jobs/7588/

**Comment by hugovk** [comment]
Thanks for the report, closing as a duplicate of #2020.
