### ISSUE TITLE
Issue with sitemap navigation menu do-not-print

### ISSUE THREAD

**Issue by mbiesiad** [proevo/pythondotorg#2050]
**Describe the bug**
Described and presented elements are not displayed correct.

**To Reproduce**
1. Go to: https://www.python.org/search
2. Click on the button 'Search' (or type something with result "**No results found**.")
3. Change the browser window size immediately (eg. with double click; see descr./notes below) to the smallest
4. Scroll down to the down (class= sitemap navigation menu do-not-print)
5. See error

**Expected behavior**
With smaller window browser size the mentioned elements still works/looks correct.

**Screenshots**

Issue [Chrome]:
![image](https://user-images.githubusercontent.com/18367606/170780162-f230b281-cad0-4e6f-aba2-af7c67cbb594.png)

Issue in other form [Chrome]:
![image](https://user-images.githubusercontent.com/18367606/170783176-00f79b57-0934-4819-b5d2-94b81d9f3b23.png)

Issue - Firefox example [1]:
![image](https://user-images.githubusercontent.com/18367606/170783363-cf73f62c-94c4-4f9b-8d78-e9dc1e695fba.png)

Issue - Firefox example [2]:
![image](https://user-images.githubusercontent.com/18367606/170783477-593a4bc3-5b49-4405-b397-027d5d128503.png)

![image](https://user-images.githubusercontent.com/18367606/170784658-9a5a654b-9bc9-4d67-9974-d13523abc665.png)

**Desktop:**
 - OS: Windows
 - Browser: Chrome as well, as Firefox
 - Version: the newest (x2; an issue upload date)

**Additional context**
The best way for reproduce this issue is to prepare your browser (browser window size/**width** with smallest size; and double click for change full-screen size to the smallest size/**width** window).

During slower resizing, it initially looks fine. Sometimes with double click (max & min size - the result is still incorrect or correct),
(take your time on your own research here, because it's quite an interesting case)

Best wishes,

**Comment by hugovk** [comment]
Thanks for the report, I was unable to reproduce with Chrome on macOS, the sections were reflowing without overlap. Does the issue still happen for you? Let's close for now.

**Comment by mbiesiad** [comment]
Hi @hugovk my pleasure! Thank you for your comment and action. Agree - looks fixed now. Best wishes,
