### ISSUE TITLE
For loop with enumirate not consistent

### ISSUE THREAD

**Issue by u20772077** [proevo/pythondotorg#2067]
Hi, python community.

Thank you very much for this powerful tool. I just want to raise a small concern, perhaps it's from my side. However, please run some tests and see if you are getting the same thing.

I am trying to run a simple for loop with enumerate and within the for loop do some activities. Here is an example of what I'm trying to do. and below ill explain what the issue is. 

Note: the following is just for the sake of explaining, it is not executable.

# function to do something

def functionA()

return answer

# list of list to iterate on.
listA = [ [some content], [some content], [some content]]

# list containing unwanted words
listB = []
# start for loop
for  lst in enumerate(listA)
                 for count, item in list B
                      if item in listB:
                             # delete, remove, or pop   --- for now lets use pop  but i the same thing remove and del
                             lst.pop(pop)

The code above works perfectly fine until it finds duplicates in the list. It then removed one of the duplicates and the other is not removed. I have traced down this problem and I think the issue is with the enumerate method. I looped through to see the counts without performing delete and all the indexes of the item were printed. But when I add the delete/pop/remove it only removes one of the duplicates. Furthermore, the index of the other item is not printed when i try to print it. only one of them("The first") is printed.

The reason why i say the problem might be with enumerate is because in my solution( which is obviously not efficient) to this, I collected all the indexes first and looped again to remove unwanted items( because I saw that just looping without the delete method all indexes are printed).  

Again, I also saw that at some point, i had to store the count( aka index) in another temporary variable for things to work .e.g

for c, item in enumerate(l):
        tempc = c
        # then use tempc instead of c
        function(tempc)          # using c straight away did not work for me

Please run some test on this and give feedback if possible. Thanks

Kind regards,
Thapelo

**Comment by Mariatta** [comment]
Your code is not formatted well. I think the problem here is that you're trying to delete items in the list while looping through the list? This is known to cause unexpected problems, and you shouldn't do it this way. I think if you search in stackoverflow you should get some clues on how to approach this problem.

 
I'm closing the issue since this issue tracker is for issues related to the python.org website, not for general programming questions about using Python.
