### ISSUE TITLE
503 expired certificate for https://downloads.python.org/pypy/versions.json

### ISSUE THREAD

**Issue by stephenmuss** [proevo/pythondotorg#2068]
**Describe the bug**
A 503 certificate expired response is returned by the Varnish Cache Server.

**To Reproduce**
1. Navigate to https://downloads.python.org/pypy/versions.json in a browser
2. See error

**Expected behavior**
A 200 successful response is returned with the pypy versions json object.

**Screenshots**
<img width="1117" alt="Screen Shot 2022-07-04 at 2 53 56 pm" src="https://user-images.githubusercontent.com/630871/177084109-1d7d4f0c-4e23-4a13-85c5-5fbfbf4e6bd4.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser Firefox 101.0

**Additional Info** 
```
$ curl https://downloads.python.org/pypy/versions.json -i                                                                                                                                                          

HTTP/1.1 503 certificate has expired
Connection: close
Content-Length: 460
Server: Varnish
Retry-After: 0
Content-Type: text/html; charset=utf-8
Accept-Ranges: bytes
Date: Mon, 04 Jul 2022 05:02:57 GMT
Via: 1.1 varnish
X-Served-By: cache-syd10164-SYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1656910977.699612,VS0,VE1163
Strict-Transport-Security: max-age=31557600


<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 certificate has expired</title>
  </head>
  <body>
    <h1>Error 503 certificate has expired</h1>
    <p>certificate has expired</p>
    <h3>Error 54113</h3>
    <p>Details: cache-syd10164-SYD 1656910978 1764653819</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by ewdurbin** [comment]
This is the certificate for the backend https://buildbot.pypy.org, the CDN is reporting and I’ve confirmed the LetsEncrypt certificate for that host expired yesterday.

I’ve notified the maintainers but have no recourse as we do not have access to the host.

**Comment by Mariatta** [comment]
Thank you for looking into this. It seems like the issue has been resolved, so I'm closing this.
