### ISSUE TITLE
Add a "How to get help" link to the front page

### ISSUE THREAD

**Issue by pfmoore** [proevo/pythondotorg#2074]
**Is your feature request related to a problem? Please describe.**
Users having trouble with a Python problem don't really have a good idea of where to go for help. As a result, they often ask in the wrong place - for example, users having problems with importing modules raise issues on the pip tracker.

**Describe the solution you'd like**
It would be good to have a very clear link on the python.org homepage saying "Where to get help" and pointing to user forums like the Users category on Discourse and comp.lang.python.

**Describe alternatives you've considered**
At the moment, this information is available via About->Help, but that's not at all obvious to a newcomer. The "Community" section seems more about how we manage the community than how to be part of the community.

**Additional context**
See [this post on Discourse](https://discuss.python.org/t/reconsider-the-users-category/3365/89?u=pf_moore) for context

**Comment by hugovk** [comment]
I'm not sure if this is new, but right now I went to https://www.python.org/ and searched for "help" which shows the About > Help in the footer menus, and "Help & General Contact" in the base footer:

<img width="1219" alt="image" src="https://github.com/user-attachments/assets/6c0bcb05-4a9f-476a-913f-9b86788a6c05">

Those both go to https://www.python.org/about/help/ which has questions pointing people to different places:

<img width="715" alt="image" src="https://github.com/user-attachments/assets/70844b61-6426-41ff-93a0-7758d6b299e2">

For example, "Got a Python problem or question?" points to the FAQ, and then the Discourse Help category, then other resources.

Do you think this is okay?

Or should we change the footer "Help" link to something more explicit like "Where to get help".

Or perhaps add another "Where to get help" elsewhere on the page? Where?

**Comment by JacobCoffee** [comment]
I think that's good, though it would be nice to mention r/LearnPython as a resource since we mention SO

also is in the header menu

![image](https://github.com/user-attachments/assets/dd8e7621-191c-48c3-8377-45b0bbf4f2c4)

**Comment by hugovk** [comment]
I've added to https://www.python.org/about/help/:

> * You can post questions and ask for general advice about your code at the [r/LearnPython](https://www.reddit.com/r/learnpython/) subreddit.

How does that look?

**Comment by JacobCoffee** [comment]
Very nice! :) Thank you.
@pfmoore let me know if you think this is inadequate or could use more
