### ISSUE TITLE
A bunch of older release pages have raw html 

### ISSUE THREAD

**Issue by anthonybaxter** [proevo/pythondotorg#2075]
I was trying to recall which releases I had done and a bunch of older release pages have raw HTML, such as

https://www.python.org/downloads/release/python-213/
https://www.python.org/downloads/release/python-231

It's pretty minor, unless it's a systemic issue for older pages.

**Comment by andersk** [comment]
These are all affected:

https://www.python.org/downloads/release/python-213/
https://www.python.org/downloads/release/python-220/
https://www.python.org/downloads/release/python-221/
https://www.python.org/downloads/release/python-222/
https://www.python.org/downloads/release/python-230/
https://www.python.org/downloads/release/python-231/
https://www.python.org/downloads/release/python-232/
https://www.python.org/downloads/release/python-233/
https://www.python.org/downloads/release/python-234/
https://www.python.org/downloads/release/python-235/

**Comment by gabrielolnunes** [comment]
Hello! I'm taking a look at the stored data and will try to open a PR for this ticket today.

**Comment by hugovk** [comment]
Thanks, I've fixed the mentioned URLs by flipping the markup type from reST to HTML:

<img width="838" alt="image" src="https://github.com/user-attachments/assets/5817307e-9603-4821-9295-95871d9ed548">
