### ISSUE TITLE
The Speech module reported an error due to a partially dependent name change in Python3

### ISSUE THREAD

**Issue by CoolPlayLin** [proevo/pythondotorg#2077]
<img width="789" alt="Snipaste_2022-07-19_20-51-15" src="https://user-images.githubusercontent.com/96709586/179754574-6268bfe4-6c32-49d5-9b9e-0908513f007e.png">
As shown in the figure, Python3 directly reports an error when referring to this module.

**Comment by Mariatta** [comment]
This issue tracker is not for general questions about Python, buy for issues related to the pythondotorg website, so I'm closing this issue.

The `speech` module is third party module that is not maintained by us. Looking at its page on PyPI, it seems to only work in Python 2. So I would not recommend using it. You should look for a module that works in Python 3.

**Comment by CoolPlayLin** [comment]
Oh no!
