### ISSUE TITLE
Hyperlink typo in PSF grants FAQ

### ISSUE THREAD

**Issue by laggron42** [proevo/pythondotorg#2082]
**Describe the bug**

In the following paragraph, the `<a href=...>` tag isn't properly closed, breaking the hyperlink and displaying raw HTML

> Q. Can we use your logo or a similar logo? How should we use the words "Python" or "PyCon"
which are trademarked?
A. Please \<a href="https://www.python.org/psf/trademarks/">read our Trademark policy>. This covers the Python logo or any similar logos and the use of the words "Python" or "PyCon" and how you should proceed. if you have any doubts about your intended use of the trademarks, please contact the [PSF Trademarks Committee](mailto:psf-trademarks@python.org).

Fix is easy

```diff
- A. Please \<a href="https://www.python.org/psf/trademarks/">read our Trademark policy>.
+ A. Please \<a href="https://www.python.org/psf/trademarks/">read our Trademark policy</a>.
```

**To Reproduce**
1. Go to https://www.python.org/psf/grants/faq/
2. Scroll down to the section "Q: Can we use your logo or a similar logo?"

**Screenshots**

<img width="671" alt="image" src="https://user-images.githubusercontent.com/23153234/180830800-9802e558-88fc-4c40-9282-c9c0f06490a3.png">

**Comment by ewdurbin** [comment]
Thank you, this has been corrected in our content management system.
