### ISSUE TITLE
The template for new tickets in this repo sends people to bugs.python.org

### ISSUE THREAD

**Issue by hop** [proevo/pythondotorg#2085]
```
Issues related to Python's documentation (https://docs.python.org) can
also be filed in https://bugs.python.org, by selecting the
"Documentation" component.
```

Well, they can't :D

/me is off to file the actual bug. Once I find the correct repo…

**Comment by Mariatta** [comment]
The URL should be updated from bugs.python.org to github.com/python/cpython

**Comment by Mariatta** [comment]
The direct URL for creating a Documentation issue for CPython is https://github.com/python/cpython/issues/new?assignees=&labels=docs&template=documentation.md

**Comment by harshvardhanb25** [comment]
@Mariatta I can fix this. Just to be sure, should I change the URL to github.com/python/cpython or to https://github.com/python/cpython/issues/new?assignees=&labels=docs&template=documentation.md?

**Comment by Mariatta** [comment]
We can use the direct url: https://github.com/python/cpython/issues/new?assignees=&labels=docs&template=documentation.md

And you don't have to say 'by selecting the "Documentation" component' anymore.

Thanks.

**Comment by harshvardhanb25** [comment]
@hop can you point me to the URL of the page where you found this error? I see these words in the readme but the error seems to have been fixed.

**Comment by hop** [comment]
Issues >> New Issue >> Bug Report or Feature Request

https://github.com/python/pythondotorg/issues/new?assignees=&labels=&template=bug_report.md
https://github.com/python/pythondotorg/issues/new?assignees=&labels=&template=feature_request.md

**Comment by harshvardhanb25** [comment]
I see. I don't think I can update the templates for this repository. I guess only a member might be able to do that.

**Comment by ewdurbin** [comment]
hi @hop what is the URL where the text you pasted is showing?

**Comment by Mariatta** [comment]
The issue template is here: https://github.com/python/pythondotorg/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

You should be able to create a pull request to edit the file.
