### ISSUE TITLE
The website use hsts but in my pc showing your connection is not 🚫 private plzz help

### ISSUE THREAD

**Issue by Pawanoo** [proevo/pythondotorg#2088]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mariatta** [comment]
It doesn't seem to be a problem about the Python dot org website, so I'm closing this issue.
