### ISSUE TITLE
ttk Styling for Option Menu 

### ISSUE THREAD

**Issue by A1827PM** [proevo/pythondotorg#2089]
I'm not getting how to apply the style on Option Menu in Tkinter using ttk module. It always raises an error either regarding _layout not found_ or _Invalid Syntax for widget "OptionMenu"_. What should I go for?

**Comment by ned-deily** [comment]
This issue tracker is for reporting problems with the Python.org website. If you need assistance with using Python, please try one of the many resources listed on the [Help page here](https://www.python.org/about/help/).
