### ISSUE TITLE
Sponsorship Admin Page: Add filter by year

### ISSUE THREAD

**Issue by oliviasauls** [proevo/pythondotorg#2096]
**Location of change**
python.org/admin/sponsors/sponsorship - Admin/Sponsorships/Filter

**Describe the solution you'd like**
Filter sponsor level by year (e.g. Visionary 2022 vs Visionary 2023)

**Reason for change**
  * Easier for admin to find active sponsorships for fulfilling benefits/reviewing contracts
  * Defining when sponsorships end and are in need of renewal and how many sponsorships a sponsor has had in the past

**Priority**
1. High

**Date Needed**
Sponsorship Launch 

**Additional context**
<img width="1596" alt="Screen Shot 2022-08-01 at 7 18 07 PM" src="https://user-images.githubusercontent.com/89146495/182446775-3e06b7e0-1b5b-4abf-bd30-e7b9c50c2ada.png">

**Comment by ewdurbin** [comment]
addressed by #2087
