### ISSUE TITLE
Sponsorship Admin Page: Add CSV output

### ISSUE THREAD

**Issue by oliviasauls** [proevo/pythondotorg#2106]
**Location of change**
python.org/admin/sponsors/sponsorship/ - Sponsorship Admin

**Describe the solution you'd like**
  * Add CSV output exporting from Sponsorship list including URL of the Sponsor page if possible
  * Contacts included in export; benefits do not need to be included

**Reason for change**
  * This will be used to enter info into this google sheet, sheet 1 “General” (we are eliminating some of the columns): [PSF Sponsorship Benefit Tracking - All Programs](https://docs.google.com/spreadsheets/d/19VmIo3FS0SkZgA4uyVu_M7r6kIduK0_Qsp_bjjWxX00/edit#gid=0). This is our primary reference/working doc for sponsorships.
  * Will also be used to copy email addresses into Compose in Gmail
  
**Priority**
2. Medium

**Date Needed**
Sponsorship Launch 

**Additional context**
Mock up here: [Mock up of CSV output from Python.admin](https://docs.google.com/spreadsheets/d/16RD-1_JAHYIwg82RuExxmhZziK31N3z8vrZA8Povrb4/edit#gid=0)
  * If any of these items are extra hard, it’s probably fine to omit them, at least at this stage. Even if we just had company name and contact names/emails, that would be a major help.

**Comment by saadmk11** [comment]
Looks like the CSV output sample provided in the issue is private, I have added a PR (https://github.com/python/pythondotorg/pull/2179) with basic fields for now. It would be great if you can provide the output format as a comment or make the spreadsheet public. :)
