### ISSUE TITLE
Sponsorship Application Form: Enforce new rules regarding non-package benefits

### ISSUE THREAD

**Issue by ewdurbin** [proevo/pythondotorg#2117]
Depends on #2116 for implementation and terminology used below.

- a la carte benefits should only be able to be applied for if a package is selected
- applications for standalone benefits should be mutually exclusive with applications for packages
- combining the two above rules, this means that applications for standalone benefits should not be able to include a la carte benefits

Additionally, packages should be configurable as to wether they allow a la carte benefits from section 2 of the form. This should also control as to wether the "potential add-on" in the benefits grid is shown.

These rules should be enforced in form validation on submission as well as represented in the UI.

Example: Associate package for the current sponsorship application will not be allowed to include any benefits not configured as part of the package in the backend.

Thus, the following selection should not be shown or enabled:

<img width="1444" alt="grid" src="https://user-images.githubusercontent.com/1200832/184016094-df61b7bd-507a-43ff-8d94-55f3b15c062d.png">

Additionally if the Associate package is selected the following two sections should not be enabled for selection, and any existing selections should be cleared.

<img width="1304" alt="after-sell" src="https://user-images.githubusercontent.com/1200832/184016309-a106d69e-cee0-439a-9716-973c764d6683.png">

**Comment by loren-c** [comment]
Hi Ee -Thanks so much for doing this and it looks great. One request - I'd prefer you don't clear any existing selections for Associate packages that have already been submitted. I've already reviewed and adjusted any that have already been submitted, and I have made at least one one-off exception for a sponsor (PRISMA) that shouldn't be changed. Thank you!!

**Comment by ewdurbin** [comment]
Yes, this functionality will only affect the sponsorship application form, so previous submissions will not be changed.

**Comment by loren-c** [comment]
Thank you!! Sorry, I had misinterpreted "Additionally if the Associate package is selected the following two sections should not be enabled for selection, and any existing selections should be cleared", got it now!!
