### ISSUE TITLE
Invalid link to Python bug tracker on 3.11rc1 release page

### ISSUE THREAD

**Issue by ichard26** [proevo/pythondotorg#2119]
On https://www.python.org/downloads/release/python-3110rc1/, under the "Call to action" header and then "Community members" subheader the last sentence contains an invalid link to the Python bug tracker. It points to `https://github.com/issues` whereas it should point to `https://github.com/python/cpython/issues`.

![image](https://user-images.githubusercontent.com/63936253/184466623-2125034d-7eb3-4771-b29a-309527a43a33.png)

---

I originally filed this in the cpython issue tracker (https://github.com/python/cpython/issues/95941), but I realized this is a better place for it.

**Comment by ewdurbin** [comment]
cc @python/python-release-managers

**Comment by pablogsal** [comment]
I have corrected this 👍

**Comment by ichard26** [comment]
There's an extra space after the link :stuck_out_tongue_closed_eyes:, but this issue can be closed :slightly_smiling_face: 

Thanks @pablogsal!
