### ISSUE TITLE
redundant period in sentence "Learn more about Python.."

### ISSUE THREAD

**Issue by partev** [proevo/pythondotorg#2143]
1. go to www.python.org
2. click on "About"
3. See an extra period in the sentence "Learn more about Python.."
4. see attached screenshot illustrating the problem.
![Screenshot 2022-09-23 17 35 13](https://user-images.githubusercontent.com/23830955/192060085-c16d9de5-31a8-4c89-b748-438ee90d3947.png)

It looks like there is one period in link name and one extra period at the end.
`[Learn more about Python.](https://staging.python.org/about).`
One of them needs to be removed like this for example:
`[Learn more about Python](https://staging.python.org/about).`

**Comment by ewdurbin** [comment]
Thank you this has been resolved in our CMS backend. It will be live after caches clear.
