### ISSUE TITLE
Python Patterns - Implementing Graphs

### ISSUE THREAD

**Issue by DaveBeCoding** [proevo/pythondotorg#2147]
**Describe the bug**
I found a small issue with the follow snippet of code found on the page titled "Python Patterns - Implementing Graphs" :

`def find_path(graph, start, end, path=[]): path = path + [start] if start == end: return path if not graph.has_key(start): return None for node in graph[start]: if node not in path: newpath = find_path(graph, node, end, path) if newpath: return newpath return None`

The above snippet should be changed to :

`def find_path(graph, start, end, path=[]): path = path + [start] if start == end: return path if start not in graph: # .has_key(start) was removed in python 3 return None for node in graph[start]: if node not in path: newpath = find_path(graph, node, end, path) if newpath: return newpath return None`

The method .has_key() is no longer supported by Python 3, [Documention](https://docs.python.org/3.0/whatsnew/3.0.html#builtins).

I am a little unsure as where this is located within the repository so that I can submit a Pull Request(s) for the handful corrections needed on this page/documention for Python.org.

**To Reproduce**
[Python Patterns - Implementing Graphs](https://www.python.org/doc/essays/graphs/)

**Expected behavior**
The below line :

`if not graph.has_key(start):`

Should be change to the following :

`if start not in graph:`

According to the documentation found [Here](https://docs.python.org/3.0/whatsnew/3.0.html#builtins).

**Screenshots**

![Section_one](https://user-images.githubusercontent.com/70411835/192545723-514aa1a3-6592-4094-947d-aae9140aa0e9.png)

![section_two](https://user-images.githubusercontent.com/70411835/192545836-14760251-36a2-4d32-b306-7b3e633daa26.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I originally submitted this issue to [Cpython Repo](https://github.com/python/cpython/issues/97573), I believe this issue is also related to the following [#1452](https://github.com/python/pythondotorg/issues/1452)

I wasn't entirely sure how to locate the documentation directly related to this issue, and submit a Pull Request with all needed changes.

**Comment by DaveBeCoding** [comment]
I have added screen shots of the exact lines that need to be updated to the Python 3 documentation standards linked above.

**Comment by Mariatta** [comment]
I think the content is stored in a CMS.
The essay is outdated indeed, it was initially written before the times of Python 3. There's also a warning at the top of the page. I'm not sure if we need to update the content.

**Comment by ewdurbin** [comment]
I agree that given the warning, we should leave the page as is.
