### ISSUE TITLE
low quality alert - remove web2py from recommended frameworks in homepage and wiki 🙏

### ISSUE THREAD

**Issue by marcomilone** [proevo/pythondotorg#2149]
Hello,
I'm a Python developer since many years.
I have been working (forced to) on web2py for last 18 months~.
We had to modify the core to correct bugs and implement missing features.

Please, please, remove it from the Python homepage.

I guess nobody managing the website never tried it, on the field. Is a real pain in the ass.

I mean please remove the adv from the
 - homepage "Use Python for…" box.
   https://www.python.org
 - wiki - frameworks
   https://wiki.python.org/moin/WebFrameworks

That framework is very dangerous,
because it is
 - written slapdash
 - many things are half implemented (e.g. DAL dialects are missing many features or bugged)
 - lacks of many today features
 - don't even try to follow our beloved "zen" in any part
 - many bad practices that should be avoided are very well implemented
 - developer user base is probably dead, except me and my colleagues

It's not a personal matter.
Honor and glory to the author and every contributor, 
but it should be rewritten from the ground up, to try to compete with present-day frameworks.

I'm writing this because I want to save someone time, to channel efforts in the right directions.
Don't be wrong. Don't. Choose. Web2py.

Feel free to ask if you need further information.
🐍❤️

**Comment by ewdurbin** [comment]
Hi @marcomilone, it sounds like most of your complaints should be addressed with the developers of web2py, which does appear active at https://github.com/web2py/web2py.

Given that this is a valid use of Python for the web and it is an active project, I do not see any reason to remove it from either place you've listed. Users can and should be trusted to review potential libraries/frameworks before selecting them.

I would also like to caution you against some of the ways you're communicating your frustration as they are borderline on the [PSF Code of Conduct](https://www.python.org/psf/conduct/) that governs this space.

**Comment by marcomilone** [comment]
Hello @ewdurbin,
I admit my words were too direct or borderline somehow (I hope the good side of the border).

But... have you ever tried web2py?

FastAPI is not even mentioned in the same box or in the "more" page, eg.

I totally agree that "_is a valid use of Python for the web_".

I sadly disagree on "_is active_" :
 - https://github.com/web2py/web2py/issues   (350 open issues, 7 years old... many are bugs, a big part of the ORM)
 - experimental branch is 7 years old
 - pydal (submodule) have 130 issue (half are bugs)

> Users can and should be trusted to review potential libraries/frameworks before selecting them.

Yes. You are right again.
But not ALL users. A big box in the main Python site should guide and help newbies and experts.
IMHO that site should avoid to offer big bad bear traps.
Btw is my opinion.

Cheers.

**Comment by marcomilone** [comment]
At least I'm not alone.


https://www.reddit.com/r/learnpython/comments/viqebv/setting_up_web2py_on_vscode/
