### ISSUE TITLE
Wrong url link for Trac on Applications for Python page.

### ISSUE THREAD

**Issue by inyong37** [proevo/pythondotorg#2150]
**Describe the bug**
A link on the applications for Python page is looking at the wrong path.

**To Reproduce**
1. Go to "https://www.python.org/about/apps/"
2. Click on "Trac"
3. ~~Scroll down to '....'~~
4. See "Error displaying page"

**Expected behavior**
Should display the correct trac main page.

**Screenshots**

Current link:
<img width="505" alt="Screen Shot 2022-10-04 at 3 14 16 PM" src="https://user-images.githubusercontent.com/20737479/193747518-305821c0-dba3-415e-b77b-8f46d08d627e.png">

Page with current link:
<img width="787" alt="Screen Shot 2022-10-04 at 3 14 30 PM" src="https://user-images.githubusercontent.com/20737479/193747554-c7d7717d-d4d7-4766-875c-2a731ee844cf.png">

Right link:
<img width="166" alt="Screen Shot 2022-10-04 at 3 17 42 PM" src="https://user-images.githubusercontent.com/20737479/193748033-0b754f4a-a348-41b4-8e88-136219e623ce.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by inyong37** [comment]
However, in `fixtures/boxes.json` file (line 177, 179), I can see the right url.

**Comment by ewdurbin** [comment]
Updated in our CMS.
