### ISSUE TITLE
Provide read access for https://www.python.org/ftp/python/3.10.8/amd64/

### ISSUE THREAD

**Issue by DimitryAndric** [proevo/pythondotorg#2154]
**Describe the bug**

See https://github.com/python/cpython/issues/98193 for more details. If people attempt to download debug symbols during python 3.10.8 installation on Windows amd64, they'll receive "403 access denied" when the installer attempts to access https://www.python.org/ftp/python/3.10.8/amd64/core_pdb.msi (and/or any other files under https://www.python.org/ftp/python/3.10.8/amd64/).

**To Reproduce**
1. Follow https://www.python.org/ftp/python/3.10.8/amd64/
2. Receive 403 Access Denied

**Expected behavior**
Expected a listing of the directory, and being able to download files under it..

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: any

**Comment by ned-deily** [comment]
Thanks for the report. However, the Python release managers are responsible for the download files associated with a release and they do not closely monitor this issue tracker. [As has already been done](https://github.com/python/cpython/issues/98193), reporting future problems like this should be done on the cpython issue tracker. The downloads should now be working.
