### ISSUE TITLE
asyncio-stream example does not work

### ISSUE THREAD

**Issue by ThaBluNate** [proevo/pythondotorg#2155]
**Describe the bug**
Documentation - asyncio-stream example does not work

**To Reproduce**
1. Go to [asyncio-stream's docs](https://docs.python.org/3.12/library/asyncio-stream.html)
2. Copy the **_example of a TCP echo client written using asyncio streams_** from the top of the page
`Traceback (most recent call last):`

  `File "E:\A\test.py", line 18, in <module>
    asyncio.run(tcp_echo_client('Hello World!'))`
  `File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)`
  `File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()`
  `File "E:\A\pynet.py", line 4, in tcp_echo_client
    reader, writer = await asyncio.open_connection(`
  `File "C:\Program Files\Python310\lib\asyncio\streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(`
  `File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1064, in create_connection
    raise exceptions[0]`
  `File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(`
  `File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)`
  `File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 705, in sock_connect
    return await self._proactor.connect(sock, address)`
  `File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)`
  `File "C:\Program Files\Python310\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()`

`ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection`

**Expected behavior**
The file is meant to echo '`Hello World`' and exit.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave, Chromium-Based browser
 - Version: 1.43.93

**Comment by siphr** [comment]
For assistance, I validated this on Linux, where it seems to work as shown in the following response dump....
```

✦ ❯ Serving on ('127.0.0.1', 8888)
✦ ❯ python tec.py 
Send: 'Hello World!'
Received 'Hello World!' from ('127.0.0.1', 41266)
Send: 'Hello World!'
Close the connection
Received: 'Hello World!'
Close the connection
```

**Comment by ewdurbin** [comment]
Hello, this is the issue tracker for issues with python.org itself, not the Python language or docs. Your issue is better filed with https://github.com/python/CPython.
