### ISSUE TITLE
Missing email notifications from Python Insider blog

### ISSUE THREAD

**Issue by pewscorner** [proevo/pythondotorg#2158]
**Describe the bug**
Maybe half a year or more ago I stopped getting emails for new Python releases in the Python Insider blog (blog.python.org). Nothing in my spam folder. Resubscribing with the same email address throws up an error stating that I'm already subscribed. Unsubscribing doesn't seem to be possible (maybe possible from within the emails I'm not getting). A couple of months ago I tried subscribing with a different email address, but still no emails.

**To Reproduce**
Subscribe to emails from blog.python.org. Wait for a new Python release. Check that no email is received.

**Expected behavior**
When subscribed to emails from blog.python.org, I should get an email for every new post.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I use Gmail.

**Comment by ewdurbin** [comment]
Hello, it seems that the feed burner integration used for email notifications is no longer functioning.

Likely the user that had set it up deactivated the feed, so it's not clear if we can restore the email subscriptions that were previously configured.

Please consider subscribing via RSS as linked in the right hand side of blog.python.org. If you'd rather retain email notifications consider an rss-to-email service.
