### ISSUE TITLE
Homepage "Latest News" is not up-to-date

### ISSUE THREAD

**Issue by jgillard** [proevo/pythondotorg#2163]
**Describe the bug**
As of 25th October, the latest news visible on the homepage is from 11th September about the Python Developer Survey. When you click the "More" link that takes you to https://blog.python.org/, there are 4 more news items available that should be visible in that homepage widget.

**To Reproduce**
1. Go to https://www.python.org/
2. Check the latest items in the "Latest News" widget
3. Press the "More" button
4. Find more recent news stories

**Expected behavior**
The latest news should be visible from the homepage.

**Screenshots**
Homepage:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/3770312/197812877-d6692e8c-6c4a-4645-a9b8-b81c5aead7e1.png">
Python Blog:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/3770312/197812993-7b3de0a9-b3e0-419c-af85-83e90628db93.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 106

**Comment by ned-deily** [comment]
Thanks for the report; the problem seems to persist. @python/infrastructure-staff, can someone take a look?

**Comment by ewdurbin** [comment]
Reported recently via email also:

> Greetings!
> 
> The RSS Feed on https://blog.python.org <https://blog.python.org> links 
> to the Python Insider RSS feed. Python Insider looks to be a mirror of 
> blog.python.org <http://blog.python.org> (or perhaps it’s the other way 
> around).
> 
> Regardless, the RSS feed currently seems to be have stopped updating 
> properly. The last RSS feed update was 2022-09-12 for “Python 3.11.0rc2 
> is now available”. On today’s exciting release date for 3.11, I was sad 
> not to see it show up in my RSS feed!
> 
> I hope you’re able to get the RSS feed back up and running!

**Comment by ewdurbin** [comment]
I'm not positive who configured/manages the feed burner setup but I'll take a look.

**Comment by ewdurbin** [comment]
Seems feedburner was 503ing for our feeds. I've configured them to load directly from the blogger feeds and all appears well now.
