### ISSUE TITLE
Remove 2.7 pointers from downloads pages

### ISSUE THREAD

**Issue by zware** [proevo/pythondotorg#2165]
2.7 is approaching 3 years out of support, I think it's time to stop pointing to it explicitly from the downloads page(s).  Historical release pointers should remain, of course, but things like the `Looking for Python 2.7? See below for specific releases` note and the 2.7 entry in the "Active Python Releases" table on https://www.python.org/downloads/, as well as the `Latest Python 2 Release - Python 2.7.18` link at the top of, e.g., https://www.python.org/downloads/source/ could be removed or reworded to make clearer that, at least from our perspective, 2.7 really has joined the choir invisible.

**Comment by ericvsmith** [comment]
I agree. Since we don't support it, I think putting it in "Active Python Releases" is misleading. It's not active to us.

**Comment by ewdurbin** [comment]
The content of that box is part of the "boxes" app. As it appears to be kept up to date with latest 3.x, I think this is a call for the @python/python-release-managers, who have access to edit it. Specifically [here](https://www.python.org/admin/boxes/box/102/change/).

**Comment by zware** [comment]
There's more than just the "Active Python Releases" box (which I assume is what you linked to; I can't see it :)), though; in particular, there's this line that can probably just be removed: https://github.com/python/pythondotorg/blob/fc9cc47f3d7038bcdd65fc4f788a19a86d7e2c87/templates/downloads/os_list.html#L32

That removal would appear to unlock quite a bit of related code cleanup (of nebulous value :)) as well.

**Comment by ambv** [comment]
I commented out the 2.7 bits from all download boxes (there were four). @zware is right we need to redeploy the website to remove Python 2 from `os_list.html`.

**Comment by ewdurbin** [comment]
Does someone want to open a PR to remove the parts from the templates?

**Comment by ambv** [comment]
I'll do that.
