### ISSUE TITLE
Add a "Markdown with HTML" option to the CMS pages

### ISSUE THREAD

**Issue by malemburg** [proevo/pythondotorg#2181]
The current CMS uses https://pypi.org/project/cmarkgfm/ for rendering Markdown syntax when selecting "Markdown" in the CMS.

This defaults to safe rendering of the given Markdown, which is fine. However, in some cases, it may be useful to e.g. make use of the available JQuery UI support for showing more advanced widgets such as accordions.

For the PSF Trademark FAQ page, it would be useful to have an option to add the needed raw HTML directly to the Markdown content (unless there's some other way to get this working): https://www.python.org/psf/trademarks-faq/ The page is becoming rather long and an accordion would help make navigation easier.

Adding support should be easy: simply add another tuple to https://github.com/python/pythondotorg/blob/main/pages/models.py#L51 using a lamdba to enable the `cmarkgfm.cmark.CMARK_OPT_UNSAFE` option. I can give this a try, if there's a chance to get this accepted.

**Comment by DavidMertz-atlantis** [comment]
An accordion would be great. I think a similar purpose would also be served if we could pin a navigation TOC to a fixed screen location.  I don't know which UI would be easier to reach, but as the main writer of that FAQ, I absolutely agree with MAL that it's becoming unwieldy.

Oh... just noticed I'm still in my work GH account for this comment. It doesn't really matter, but you can pretend it's from `DavidMertz` instead. :-)

**Comment by malemburg** [comment]
With the change that Ee is working on, we'll have more options. The accordion is the easiest to implement on the page: https://jqueryui.com/accordion/#default so let's start with that one.

**Comment by malemburg** [comment]
I tested the PR on staging and it does allow adding raw HTML to the page content. Unfortunately, <script> tags are still disabled by converting the first "<" to `&lt;`. Will have to do some more investigation on why this is happening.

**Comment by malemburg** [comment]
Took a while to analyze (getting the docker container setup and working, grepping through tons of code). I eventually tracked this down to `cmakegfm.github_flavored_markdown_to_html()` applying the quoting, even when UNSAFE is set.

**Comment by malemburg** [comment]
The Github version of cmake applies additional tag filters per default: https://github.com/github/cmark-gfm/blob/master/extensions/tagfilter.c These include the script tag. The extension can be disabled, but we can then no longer use the `cmakegfm.github_flavored_markdown_to_html()` API.

**Comment by malemburg** [comment]
The changes for the TM FAQ page have now been put in place: https://www.python.org/psf/trademarks-faq/
It is much easier to navigate than before.
