### ISSUE TITLE
python.org CRITICAL: ALL DOWNLOADS DIGITAL SIGNATURES FAIL - WITH NO INSTRUCTIONS - URGENT

### ISSUE THREAD

**Issue by KonanTheLibrarian** [proevo/pythondotorg#2184]
**Mind Numbing Lack of Python download package Security Verification - EVEN AT THE BRINK OF WAR**
python.org hides the .asc and .sig files on the download pages, provides no security verification instructions and gpg --verify FAILS!

**To Reproduce**
Steps are in more detail below. Find the python.org downloads for the latest python packages eg for amd64 exe file.
Look for gpg digital signatures NONE. It is wartime so be puzzled!  Be determined, take the download link and delete the filename off the end.  Browse into the repository directory index of files.  In the browser search for Oct-2022 (latest release date) download the files including your package and the matching .asc and .sig used by gpg --verify to verify the integrity. Then verify with gpg.

1. [Go to 'python download page'](https://www.python.org/downloads/windows/)
2. Hover, right-click Copy the link to a python download eg https://www.python.org/ftp/python/3.11.0/python-3.11.0-amd64.exe
3. Past into new browser tab but delete the filename off the end. https://www.python.org/ftp/python/3.11.0/ 
4. Search for Month-Year of release date, see they are highlighted eg Oct-2022
5. Download all the files for that package, executable, .sig file and .asc file. 
6.  In a bash shell verify the files
``` bash
gpg --verify python-3.11.0-amd64.exe.asc python-3.11.0-amd64.exe
gpg: Signature made Mon Oct 24 19:53:03 2022 GMTST
gpg:                using RSA key FC624643487034E5
gpg: Can't check signature: No public key

Ok as expected so far but remember you are NOT giving the public instructions. 

Remedy may be right or wrong, but does something:
gpg --recv-keys FC624643487034E5

gpg: /c/Users/xxxxxxx/.gnupg/trustdb.gpg: trustdb created
gpg: key FC624643487034E5: public key "Steve Dower (Python Release Signing) <steve.dower@microsoft.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1

Try again to verify worse problem with .sig files
gpg --verify python-3.11.0-amd64.exe.asc python-3.11.0-amd64.exe

gpg: Signature made Mon Oct 24 19:53:03 2022 GMTST
gpg:                using RSA key FC624643487034E5
gpg: Good signature from "Steve Dower (Python Release Signing) <steve.dower@microsoft.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7ED1 0B65 31D7 C8E1 BC29 6021 FC62 4643 4870 34E5

```

**Expected behavior**
I expect your digital signatures to work or at least provide instructions that may NOT be the same as above.
Instructions that are also trusted.  Then if the public notices a broken file security alerts can be created.

**Additional context**
Threat of world digital collapse at time of war.  Shear ignorance at python.org

**Comment by KonanTheLibrarian** [comment]
### CRITICAL the .sig file appears to be FAKE, which is a major critical security problem URGENT INVESTIGATION NOW PLEASE
You may need to shut down python.org web page!  Find out who generated the .sig dumpster fire file.
``` bash
Example with .sig file:
gpg --verify python-3.11.0-amd64.exe.sig python-3.11.0-amd64.exe
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.

$ sha256sum py*
b5884fa3f05f88bbb617d08584930770c00bbcf675f2865a9161c2358829b605 *python-3.11.0-amd64.exe
109ab0ff5c6f8f369175cbf2f2a2c1eb8d1a8f878ce3d8d5e334cf337d8c833e *python-3.11.0-amd64.exe.asc
1fce8b5e4137e235dc1e3af39795b215efefd10fa8b7a304b6c574f16851e15f *python-3.11.0-amd64.exe.crt
df94752e1dd371d57cea4b07e6e8455d4429f0afab2ba691e35c3c5773ad7a3b *python-3.11.0-amd64.exe.sig

$ md5sum py*
4fe11b2b0bb0c744cf74aff537f7cd7f *python-3.11.0-amd64.exe
4bf067fdc9c47fec8f37cda8fc8c348b *python-3.11.0-amd64.exe.asc
7bda92a91ec98e59b2fd382b7e7a7225 *python-3.11.0-amd64.exe.crt
1e1804c8d1d102e3cd3b8ec7a817d53d *python-3.11.0-amd64.exe.sig
```
Yes it is the first file: python-3.11.0-amd64.exe.sig seems to be CORRUPT, just there for show!  SUSPICIOUS!

**Comment by Mariatta** [comment]
Instructions on how to verify are written at the very bottom of https://www.python.org/downloads/

I found your message to be offensive and threatening and not inline with the PSF's code of conduct.
