### ISSUE TITLE
PSF membership FAQ missing 

### ISSUE THREAD

**Issue by pauloxnet** [proevo/pythondotorg#2185]
**Describe the bug**
The PSF Membership FAQ page linked in the PSF Landing page return a 404 page.

**To Reproduce**
1. Go to 'https://www.python.org/psf-landing/'
2. Click on 'Membership FAQ'
3. See a 404 error page

**Expected behavior**
I expect to see the Membership FAQ page

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 13
 - Browser: Firefox 
 - Version: 106.1.0

**Comment by sumit4613** [comment]
Hey, @pauloxnet I tried to figure out what's going on here. And it seems that `psf_membership` flag is off that's why you're seeing this 404.

**Comment by hugovk** [comment]
This looks fixed now.

1. Go to https://www.python.org/psf-landing/
2. Click the "Membership FAQ" button
3. It takes you to https://www.python.org/psf/membership-faq/

**Comment by pauloxnet** [comment]
> This looks fixed now.

Yes, I confirm it's fixed.
