### ISSUE TITLE
Python Logo Only Device has Empty Rectangle Below It

### ISSUE THREAD

**Issue by flywire** [proevo/pythondotorg#2186]
**Describe the bug**

Python _Logo Only Device_ svg has empty rectangle below it.

**To Reproduce**

1. https://www.python.org/community/logos/
2. Download [SVG format of only "two snakes"](https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/files/python-logo-only.svg)
3. Open in Inkscape

**Expected behavior**

Logo device only should be Logo device only, not have an empty rectangle below it.

**Screenshots**

![image](https://user-images.githubusercontent.com/11288701/200145569-55d30c1a-1f0c-43fe-a492-5a8ccd0df9b9.png)

**Desktop (please complete the following information):**

Inkscape 1.2.1 (9c6d41e410, 2022-07-14)

    GLib version:     2.72.2
    GTK version:      3.24.34
    glibmm version:   2.66.4
    gtkmm version:    3.24.6
    libxml2 version:  2.9.14
    libxslt version:  1.1.35
    Cairo version:    1.17.6
    Pango version:    1.50.7
    HarfBuzz version: 4.4.1

    OS version:       Windows 10 21H2

**Comment by flywire** [comment]
Suggested:

![python-logo-only](https://user-images.githubusercontent.com/11288701/200147074-936722ad-e522-4b65-aa58-0e5af22937e8.svg)

**Comment by Mariatta** [comment]
I think the rectangle you're referring to is there intentionally, it looks like a "shadow" to me. But I'm not the creator of the logo...

**Comment by flywire** [comment]
Yes, since you mention it, I agree but interestingly the colour is not apparent in Inkscape. It's also inconsistent when you look at the python powered logo which has no shadow. 

Still seems worthwhile reviewing the Logo device. There is no point having something as part of a logo when it is so subtle that most people using the logo omit it.

**Comment by karlafalcao** [comment]
I agree with Mariatta's. 
I think the shadow fits pretty nice to this logo and the pythondotorg page as well, as it has a bit of 3D. 
Its ok to not add the shadow if you want to use the flat version.

**Comment by hugovk** [comment]
I believe the shadow is intentional. However, if you're editing the image, it's trivial to edit it out using an SVG editor like like Inkscape. I did this for the https://helsinki-python.github.io/ logo.

Thanks for the report, let's close this.
