### ISSUE TITLE
"Issue Tracker" links to an old issue tracker

### ISSUE THREAD

**Issue by partev** [proevo/pythondotorg#2189]
**Describe the bug**
The link to "Issue Tracker" links to https://bugs.python.org/ which is the old python issue tracker. It should point to the new one which is https://github.com/python/cpython/issues

**To Reproduce**
1. Go to 'www.python.org'
2. Scroll down to bottom of the page
3. Click on 'Issue Tracker'

**Expected behavior**
Expect to be taken to https://github.com/python/cpython/issues instead of being taken to https://bugs.python.org/

**Screenshots**
![Screenshot 2022-11-08 23 58 44](https://user-images.githubusercontent.com/23830955/200742611-0edaff0b-7088-40ad-a71a-8c8f045b1939.png)

**Comment by HigorMonteiro** [comment]
this issue has been closed in  https://github.com/python/pythondotorg/issues/2054

**Comment by partev** [comment]
but it still hasn't been fixed on www.python.org

**Comment by willingc** [comment]
The footer's link for "Issue Tracker" still directs to bugs.python.org.
![Screenshot 2024-02-22 at 12 38 17 PM](https://github.com/python/pythondotorg/assets/2680980/0b00638a-7d6d-4dc9-9c41-a832968b7350)

PR #2318 and Issue #2317 should have resolved this to point to github issues. @hugovk @ewdurbin Is there something else that needs updating (nginx conf?)? (I tried to find the culprit but the boxes/sitetree/django urls are a bit confusing).

**Comment by hugovk** [comment]
https://github.com/python/pythondotorg/pull/2222 is still open, but I think this footer link is in the CMS?

**Comment by ewdurbin** [comment]
Yeah, footer link is part of nav and has been updated. Will take some time to clear fully due to CDN.

**Comment by willingc** [comment]
Thanks @ewdurbin and @hugovk for the quick response. This is working now as it has cleared the CDN. You both rock.

**Comment by willingc** [comment]
Feel free to close the issue now @ewdurbin as I don't have sufficient privileges to do so. :smile:

**Comment by partev** [comment]
confirming that this issue indeed has been fixed

**Comment by partev** [comment]
reopening the issue since it is still present at the bottom of the https://www.python.org/downloads/ page

**Comment by willingc** [comment]
@partev Verifying that I see the same behavior that you do for the downloads page. Why would the footer differ across pages?

**Comment by ewdurbin** [comment]
This is caching. It will take up to 24 hours to clear in the CDN as noted

> Will take some time to clear fully due to CDN.

**Comment by partev** [comment]
confirming that it was just a caching issue and all is working now.
