### ISSUE TITLE
Website home page, in the code example 5(Quick & Easy to Learn) has SyntaxError in first line at https://www.python.org/ .

### ISSUE THREAD

**Issue by ozgurturkiye** [proevo/pythondotorg#2190]
**Describe the bug**
Website home page, in the code example 5(Quick & Easy to Learn) has SyntaxError in first line at https://www.python.org/ .
```python
# Simple output (with Unicode)
>>> print(\"Hello, I'm Python!\")

print(\"Hello, I'm Python!\")
           ^
SyntaxError: unexpected character after line continuation character
```

**Screenshots**
<img width="543" alt="Screenshot 2022-11-10 at 1 59 00 PM" src="https://user-images.githubusercontent.com/8600407/201183516-d3e35b58-a58c-46f0-9f44-a5483cadce8f.png">

**Comment by hugovk** [comment]
This was fixed by #2191:

<img width="488" alt="image" src="https://github.com/user-attachments/assets/4dec14bf-6a3d-45d4-9f73-2f6afb4d234f">

```pycon
Python 3.13.0rc2 (v3.13.0rc2:ec610069637, Sep  6 2024, 17:57:29) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print("Hello, I'm Python!")
Hello, I'm Python!
>>>
```
