### ISSUE TITLE
List 64-bit Windows Installer Above 32-bit Windows embedded

### ISSUE THREAD

**Issue by elibroftw** [proevo/pythondotorg#2194]
**Is your feature request related to a problem? Please describe.**

Many new comers to programming start with Python. It is not safe to assume that these newcomers will understand the difference between 32-bit and 64-bit. If Python already promotes 64-bit over 32-bit on the main download, then for users upgrading within the same minor version (3.10.X -> 3.10.Y), this promotion should remain. The Windows 64-bit installer is most likely the most downloaded binary yet it is at the bottom of the list.

https://www.python.org/downloads/release/python-3108/
https://www.python.org/downloads/windows/

**Describe the solution you'd like**

I'd like the Windows downloads to be sorted as follows:

[Windows installer (64-bit)](https://www.python.org/ftp/python/3.10.8/python-3.10.8-amd64.exe)
[Windows installer (32-bit)](https://www.python.org/ftp/python/3.10.8/python-3.10.8.exe)
[Windows help file](https://www.python.org/ftp/python/3.10.8/python3108.chm)
[Windows embeddable package (64-bit)](https://www.python.org/ftp/python/3.10.8/python-3.10.8-embed-amd64.zip)
[Windows embeddable package (32-bit)](https://www.python.org/ftp/python/3.10.8/python-3.10.8-embed-win32.zip)

**Describe alternatives you've considered**

Status quo

**Additional context**
![image](https://user-images.githubusercontent.com/21298211/201535614-852c5db2-744a-4a7b-9b91-cd13dbae6e89.png)
![image](https://user-images.githubusercontent.com/21298211/201535647-3481991a-af7f-4728-92eb-6db5c3857384.png)

**Comment by OttomanZ** [comment]
I believe there is a recommended sign there, should be enough for them to know.

**Comment by elibroftw** [comment]
I believe there is **no** recommended sign there, should **not** be enough for them to know. 

<details><summary>your response is unhelpful</summary>

There's no reason to make suggestive comments on an objective discussion. "belief" is not evidence and should not be used as an argument.

</details>

**Comment by gpshead** [comment]
Per https://discuss.python.org/t/consider-downgrading-windows-32-bit-from-tier-1-to-tier-2-or-tier-3-in-python-3-13/33719 the one actual agreement we all have in that thread is that it should be more difficult to find the 32-bit x86 windows Python installers.

Only a very small percentage of people ever need them. Much of the Python software ecosystem on PyPI no longer provides 32-bit x86 windows wheels so someone unintentionally getting the 32-bit legacy version won't have a good experience.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/pythondotorg/pull/2311.

**Comment by hugovk** [comment]
Here's an example of someone on 64-bit Windows who just happened to pick the 32-bit installer and then ran into problems due to a lack of 32-bit wheels:

https://github.com/python-pillow/Pillow/issues/7454#issuecomment-1756473674

It worked after they used the 64-bit installer.

**Comment by ghost** [comment]
Yeah, I just used py 3.11.5 64 bit and it worked

**Comment by hugovk** [comment]
Another example of someone running into problems with 32 bit, solved when installing 64 bit instead:

https://stackoverflow.com/a/77321184/724176

**Comment by merwok** [comment]
Sorry, what is the point of listing these examples here? Are you facing opposition to the PR?

**Comment by hugovk** [comment]
The point is to try to illustrate that people are unintentionally installing 32-bit, but I can refrain from adding more.

No opposition to the PR, but no merge either :)

**Comment by hugovk** [comment]
Here's some more ideas. Some programming languages have a banner with featured downloads, and extra guidance text recommending 64-bit over 32-bit.

# Node.js

For example, [Node.js](https://nodejs.org/en/download/) has the 64-bit Windows installer, a macOS installer and the source tarball above the full table: 

![image](https://github.com/python/pythondotorg/assets/1324225/d7719822-e6aa-42cd-a791-379903956c8a)

# Go

Similarly, [Go](https://go.dev/dl/) shows the 64-bit Windows installer next to macOS installers and Linux and source tarballs. These files are also in bold in the full table:

![image](https://github.com/python/pythondotorg/assets/1324225/d151cfee-f41c-4ec1-b1f1-fbb5bc746e2a)

# Ruby

The [Ruby installer for Windows](https://rubyinstaller.org/downloads/) puts the 64-bit installer in bold next to an arrow, along with "Not sure what version to download? Please read the right-hand column for recommendations" which recommends 64-bit, and doesn't recommend the 32-bit:

![image](https://github.com/python/pythondotorg/assets/1324225/a7349b5c-565c-4c9f-ae8b-f8eefbc68274)

# PHP

The [PHP for Windows](https://windows.php.net/download) page puts the 64-bit downloads first, and in bold:

![image](https://github.com/python/pythondotorg/assets/1324225/ea509c23-c04a-44c4-8994-0df45e2d8fc6)

Further down in the left sidebar a recommendation for x64 builds:

![image](https://github.com/python/pythondotorg/assets/1324225/f6b3eed6-f4a3-4167-bf15-9faa21e4e137)

**Comment by stonebig** [comment]
Put the 32bit build after the others links, under a paragraph "build for legacy Windows 32 bit applications" ?

Also a written end-limit on download page may avoid an "abrupt" annoucement, like "3.13 will be the last version supporting Windows 32 bit", as Windows will end support of Windows 10 32bit around python-3.14 release

**Comment by OttomanZ** [comment]
I have been following this post for a good part of about an year. And I believe that this PR should be merged and respected by mentioning or in the very least recommending the 64-bit installer above the 32-bit install on python.org

Due to the long conversation on this thread, I believe that we should ask the creator of Python itself to hopefully bless us with his approval in merging this @gvanrossum .
> Here's some more ideas. Some programming languages have a banner with featured downloads, and extra guidance text recommending 64-bit over 32-bit.
> # Node.js
> 
> For example, [Node.js](https://nodejs.org/en/download/) has the 64-bit Windows installer, a macOS installer and the source tarball above the full table:
> 
> ![image](https://private-user-images.githubusercontent.com/1324225/293741649-d7719822-e6aa-42cd-a791-379903956c8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDYwNTYsIm5iZiI6MTcwNTI0NTc1NiwicGF0aCI6Ii8xMzI0MjI1LzI5Mzc0MTY0OS1kNzcxOTgyMi1lNmFhLTQyY2QtYTc5MS0zNzk5MDM5NTZjOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTUyMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2MzODA1YWMyOTZlNWRhNjhkOWNjNmMxMDljMGI3N2M3NjJkMTY1ZjI0NmJiNmJjNmExNTJlMTk1MzM5NzA4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eVdQWO-fFvMedd2w7G7V8Zg4jIFVG1H68gWEZCNY6N4)
> # Go
> 
> Similarly, [Go](https://go.dev/dl/) shows the 64-bit Windows installer next to macOS installers and Linux and source tarballs. These files are also in bold in the full table:
> 
> ![image](https://private-user-images.githubusercontent.com/1324225/293741911-d151cfee-f41c-4ec1-b1f1-fbb5bc746e2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDYwNTYsIm5iZiI6MTcwNTI0NTc1NiwicGF0aCI6Ii8xMzI0MjI1LzI5Mzc0MTkxMS1kMTUxY2ZlZS1mNDFjLTRlYzEtYjFmMS1mYmI1YmM3NDZlMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTUyMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzcxYjM0MGJlMjUxNjU4MmY3ZmZkMTY5ZmFkNGYxYzUwM2E3NmNlNDI4NDhlNTEyM2IzN2M5YjcxYWNjMmY1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.b9XL26UwH4BbSuFUFcJFG2m7VqxzgALrg_QgDEQFMbI)
> # Ruby
> 
> The [Ruby installer for Windows](https://rubyinstaller.org/downloads/) puts the 64-bit installer in bold next to an arrow, along with "Not sure what version to download? Please read the right-hand column for recommendations" which recommends 64-bit, and doesn't recommend the 32-bit:
> 
> ![image](https://private-user-images.githubusercontent.com/1324225/293742613-a7349b5c-565c-4c9f-ae8b-f8eefbc68274.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDYwNTYsIm5iZiI6MTcwNTI0NTc1NiwicGF0aCI6Ii8xMzI0MjI1LzI5Mzc0MjYxMy1hNzM0OWI1Yy01NjVjLTRjOWYtYWU4Yi1mOGVlZmJjNjgyNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTUyMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM3MzY0OTBkZWQxYWI3NWViZjVlZWI2OGQzNjlmMTJkNjg0ODhmNzFlNzU0NzQ2ZGM5MzI0NzNmOTU4NzU0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5k3fZxKwgmKgb-DXAefC1-5FfcD9Foc_BocT21yCJck)
> # PHP
> 
> The [PHP for Windows](https://windows.php.net/download) page puts the 64-bit downloads first, and in bold:
> 
> ![image](https://private-user-images.githubusercontent.com/1324225/293742800-ea509c23-c04a-44c4-8994-0df45e2d8fc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDYwNTYsIm5iZiI6MTcwNTI0NTc1NiwicGF0aCI6Ii8xMzI0MjI1LzI5Mzc0MjgwMC1lYTUwOWMyMy1jMDRhLTQ0YzQtODk5NC0wZGY0NWUyZDhmYzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTUyMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTlhZDBkYWRhYzc5NTZhMDIxN2M4M2Y3YmIzODAzMWQxZjNmNGE0ZjYyZDI0OGU0MDMyODM5OGZiNzgxNGY1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lQ0ozxoiPasqayrrokAMDzvjeYjfM1jhFwXG-yiGWnk)
> 
> Further down in the left sidebar a recommendation for x64 builds:
> 
> ![image](https://private-user-images.githubusercontent.com/1324225/293743028-f6b3eed6-f4a3-4167-bf15-9faa21e4e137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDYwNTYsIm5iZiI6MTcwNTI0NTc1NiwicGF0aCI6Ii8xMzI0MjI1LzI5Mzc0MzAyOC1mNmIzZWVkNi1mNGEzLTQxNjctYmYxNS05ZmFhMjFlNGUxMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTUyMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmUwZTE5ZmJjYzAzYjU2NmNmNTA0ZjcwZjIyNWFiZWM2YzgxMGNiNmFjY2UzNjlmODlkNzVhMTE3ZTY4NjlmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hLWKwUWVbyokIVBCZ3xzfAC4kPXL4Nrn_1Pdc4CQEso)

**Comment by merwok** [comment]
Appeal to authority is not helpful. That’s not how Python projects work; volunteers give their time and effort freely, but under their conditions, and things get changed when their discussion reaches a conclusion and someone with the power to merge has the time to do so.
