### ISSUE TITLE
404 in "PSF>>> Membership" breadcrumbs

### ISSUE THREAD

**Issue by hugovk** [proevo/pythondotorg#2198]
**Describe the bug**

There's a 404 error when clicking a middle breadcrumbs link. 

**To Reproduce**
1. Go to https://www.python.org/psf/members/
2. Click on Membership in the "PSF>>> Membership>>> Membership roster" breadcrumb links 
4. Shows 404 error at https://www.python.org/psf/membership/ 

**Expected behavior**

Takes you to the relevant page. 

Or the breadcrumb link should be removed. 

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 12
 - Browser Chrome 107

**Comment by Mariatta** [comment]
I think this has been addressed. At least https://www.python.org/psf/membership/ is not a 404.

**Comment by hugovk** [comment]
Yep, looks like the PSF pages have been redesigned so the breadcrumbs no longer exist.

> 1. Go to [python.org/psf/members](https://www.python.org/psf/members/)

This page is now 404, and should redirect somewhere. I've opened a new issue: https://github.com/python/pythondotorg/issues/2210
