### ISSUE TITLE
content: Typo in PSF Awards page

### ISSUE THREAD

**Issue by Mariatta** [proevo/pythondotorg#2205]
https://www.python.org/community/awards/psf-awards/

"Free registration at all future PyCon US evenns"
It should be "events" instead of "evenns".

<img width="364" alt="Screen Shot 2022-12-06 at 2 27 12 PM" src="https://user-images.githubusercontent.com/5844587/206037330-0638a33d-b134-4329-a736-ab1e162747e8.png">

**Comment by joncle** [comment]
This has been changed.

**Comment by Mariatta** [comment]
Thanks.
