### ISSUE TITLE
Type in Schedule date

### ISSUE THREAD

**Issue by jagadeeshchoudhary** [proevo/pythondotorg#2209]
**Describe the bug**
The next pre-release of Python 3.12 will be 3.12.0a4, currently scheduled for 2022-01-09. The date should be 2023-01-09.

**To Reproduce**
1. [Go to 'https://www.python.org/downloads/release/python-3120a3/']
3. Scroll down to next pre-release of python schedule date.

**Expected behavior**
2023-01-09.

**Screenshots**
<img width="467" alt="Screenshot 2022-12-08 at 11 41 54 PM" src="https://user-images.githubusercontent.com/75203040/206534609-e59b6cda-3c91-487f-b4cf-24a310c28a8d.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave
 - Version: 1.46

**Smartphone (please complete the following information):**
 - Device: Realme XT
 - OS: Android 11
 - Browser: Brave
 - Version: 1.46

**Comment by Mariatta** [comment]
cc @Yhg1s as RM for Python 3.12

**Comment by Yhg1s** [comment]
Very tempted to close as "Works as intended" because it can't _possibly_ be nearly 2023 already.... But fixed, thanks :)

**Comment by Mariatta** [comment]
Thanks
