### ISSUE TITLE
python.org/psf/members is 404

### ISSUE THREAD

**Issue by hugovk** [proevo/pythondotorg#2210]
**Describe the bug**

The PSF pages have been redesigned, and some pages renamed/moved without adding redirects, meaning existing links, both inside python.org and on external pages, now lead to 404s.

Appropriate redirects should be added.

**To Reproduce**
1. Go to https://www.python.org/psf/members/
2. Error 404: File not Found

Or:

1. Go to https://www.python.org/psf/faq/#who-are-psf-members
2. Click the link to the [membership roster](https://www.python.org/psf/members)
3. Error 404: File not Found

Or:

1. Go to https://www.python.org/psf/faq/#who-are-on-the-psf-board-who-are-the-officers
2. Click the link to the [membership roster](https://www.python.org/psf/members)
3. Error 404: File not Found

**Additional context**

The page used to be a membership roster of officers, board of directors, bloggers, members (including a list of fellows):

* https://web.archive.org/web/20221016200137/https://www.python.org/psf/members/

This has now been split out to at least:

* officers and board members: https://www.python.org/psf/board/
* fellows roster: https://www.python.org/psf/fellows-roster/

And there's also:

* FAQ: https://www.python.org/psf/membership-faq/

**Expected behavior**

https://www.python.org/psf/members/ has an automatic redirect to an appropriate general-purpose members page (because we don't know if incoming links were interested in board members, directors or fellows).

And internal links to https://www.python.org/psf/members/ are replaced/updated/removed with specific links (because we know the context of our own internal links).

**Comment by cacoze** [comment]
Hey @hugovk , I'm looking into contributing to this repository today, so I"ll be submitting a PR for this one soon.

**Comment by cacoze** [comment]
Hey folks, I can't find the following URLs/templates in the `main` branch files,  so I can't update the outdated links.
- https://www.python.org/psf/membership/
- https://www.python.org/psf/board/
- https://www.python.org/psf/fellows-roster/

Could someone tell me why?

**Comment by marksweb** [comment]
@cacoze There's a good chance it's database driven content - perhaps part of the pages app.

**Comment by cacoze** [comment]
Okay. if that's the case, I don't see any related fixture/data migration file related to this content, so I would assume that this content was directly added in production.

**Comment by indepndnt** [comment]
I've removed the links to this page from the PSF FAQ page, and added a redirect from /psf/members/ to /psf/fellows-roster/ (because judging by the archive page, this page seems to predate other types of membership). I think this issue can be closed.

**Comment by hugovk** [comment]
@indepndnt Thank you!
