### ISSUE TITLE
PSFMember site not sending password reset email for my account

### ISSUE THREAD

**Issue by lisad** [proevo/pythondotorg#2213]
**Describe the bug**
In trying to sign up to be a PSFMember, I tried to first receive an email confirmation of my account, then when I never received that, tried to do a password reset.  I tried again the next day to trigger a password reset.  None of these emails ever seemed to arrive..

**To Reproduce**
1. Go to https://psfmember.org/
2. Enter my email address and the password I tried to set
3. Get an error. Error: Invalid Password.
4. Click "Lost your password?"
5. Enter my email address
6. Go search my inbox, spam folder and entire email account...

**Expected behavior**
I should receive an email for password reset.

**Screenshots**
![Screen Shot 2022-12-14 at 3 39 30 PM](https://user-images.githubusercontent.com/484337/207738686-9d1c5a47-8c90-40a3-850c-b4d38181c287.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Firefox 107.0.1

**Additional context**

**Comment by CandaceSoVan** [comment]
I have been having the exact same issue. The site no longer recognizes my password. I request an email to reset my password. No email arrives. Happened today and yesterday (or the day before). BTW, I am trying to make a donation, but since I can't log in, it's not going through. So, this problem is preventing at least some folks from making contributions to PSF.

**Comment by tiidadavena** [comment]
I just created the account and requested a new password, however the password reset steps has worked as expected. 
![image](https://user-images.githubusercontent.com/12106738/209859296-3cae822d-eebd-4789-9bcf-b5d2f6c2261e.png)

**Comment by CandaceSoVan** [comment]
I can log into Python.org successfully, unless I'm trying to donate to the
organization. Then it says the password is wrong. So I ask for an email to
reset my password. Said email never arrives. I request again and again, and
still no email. There is a problem here that is preventing me from donating
money to the organization. Doesn't anyone care?

**Comment by indepndnt** [comment]
This issue can be closed. The emails are working and this doesn't relate to python.org, and as far as I can tell everyone involved has since logged in to psfmember.org.

**Comment by lisad** [comment]
I've tried again to log into psfmember.org or reset my password, and I still can't do either. The password I have in my password manager doesn't work, and I never get a password reset email at my email address lisa@rtfm.com.

**Comment by indepndnt** [comment]
@lisad There is no account on psfmember.org with that email address. You can create a new account, and if there are any contribution, membership, or grant records that should be linked to you, please email us at psf-donations@python.org with more information so we can find them and link them to your new account.

**Comment by JacobCoffee** [comment]
As @indepndnt said, psfmember.org is its own service and unrelated to python.org or this repo. Closing :)
