### ISSUE TITLE
we an not download older version there are some error

### ISSUE THREAD

**Issue by shivansh4123** [proevo/pythondotorg#2214]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mariatta** [comment]
Can you clarify which older version are you looking for?

**Comment by Melvinu13** [comment]
Yes, please clarify. I'd love to help out.

**Comment by hugovk** [comment]
Closing due to lack of information.
