### ISSUE TITLE
Broken link to python-ideas mailing list archive

### ISSUE THREAD

**Issue by jayaddison** [proevo/pythondotorg#2223]
**Describe the bug**
On the python.org "Mailing Lists" page, the hyperlink to ActiveState's archive of the `python-ideas` mailing list (`URL: https://code.activestate.com/lists/python-ideas/`) is broken.

**To Reproduce**
1. Go to https://www.python.org/community/lists/
2. Scroll down to 'python-ideas mailing list'
3. Click the 'ActiveState archive of python-ideas' hyperlink
4. See HTTP 404 error

**Expected behavior**
The hyperlink should be updated, or perhaps replaced/removed if ActiveState no longer archives the list.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jayaddison** [comment]
As a suggestion for a replacement (preferring that over removing the link): `mail-archive.com` includes an archive of the `python-ideas` mailing list:

https://www.mail-archive.com/python-ideas@python.org/

**Comment by jayaddison** [comment]
(note: resolving this with a pull request might not be straightforward; the URLs and text to display alongside them are loaded from the database)

**Comment by hugovk** [comment]
Thanks for the report, I've replaced the broken ActiveState link with https://www.mail-archive.com/python-ideas@python.org/.

https://www.python.org/community/lists/
