### ISSUE TITLE
Updated template for sponsorship agreements in python.org/admin/sponsors

### ISSUE THREAD

**Issue by loren-c** [proevo/pythondotorg#2235]
**Is your feature request related to a problem? Please describe.**
The current template has some errors and some items that are out of date.

**Describe the solution you'd like**
I'd like this file (track changes are on to show changes) to replace the current template file : https://docs.google.com/document/d/15tHHRLoOCI4zBOhuE60I_bg6pJFk8x6U/edit

**Comment by ewdurbin** [comment]
It doesn't look like the Google Doc is based on the template from this repository (which includes all of the template syntax that makes things work).

Differentiating the two isn't trivial. The two methods for getting changes in are:

1) Using OpenOffice locally to edit https://github.com/python/pythondotorg/blob/main/templates/sponsors/admin/contract-template.docx, committing the changes, and opening a Pull Request describing them.
2) Bullet pointing the necessary changes to the current template.

**Comment by loren-c** [comment]
Thank you, Ee! I couldn't figure out how to find that template in the repository. 
I made edits locally and submitted a pull request: https://github.com/python/pythondotorg/pull/2236#issue-1560232191

I included a link to the updated template file, but I'm not sure I set up the pull request properly to actually update the file.
