### ISSUE TITLE
Update Other Download with information about C-Python port for UEFI environment

### ISSUE THREAD

**Issue by jpshivakavi** [proevo/pythondotorg#2251]
**Describe the bug**
The webpage - https://www.python.org/download/other/ has information about the Python ports done for other platforms from different communities.

I am raising this ticket to get this page updated with the information about standard C Python 3.6.8 version port done for the UEFI environment.

Where UEFI stands for Unified Extensible Firmware Interface which provides a pre-OS environment that typically used for Firmware validation, debug, board validation, diagnostics and various other use cases.
The C-Python 3.6.8 port for UEFI provided the Advanced Python scripting capabilities on UEFI shell. This can be potentially used by a lot of device manufacturers (OEMs and ODMs), System designers, Firmware developers/validation and debug engineers for client and server systems.

By having information about this port documented the above mentioned page, we want to bring awareness about this port to potential users. This will intern help them use and contribute back if they can.
The primary idea here is to bring to the awareness of the larger Python community about this interesting Python port for UEFI environment.

We want the following documentation details to be captured in the download/other page.

""""""""
Python for UEFI Environment

Standard C-Python version 3.6.8 port for the Unified Extensible Firmware Interface (UEFI) shell environment is available through the [Tianocore](https://www.tianocore.org/) open source project.
This provides the standard C-Python scripting capabilities on UEFI environment.
Helping the UEFI based firmware and platform developer community to use it for Platform, Firmware validation, debug and etc.
Python for UEFI source code and build instructions available @ https://github.com/tianocore/edk2-libc/blob/master/AppPkg/Applications/Python/Python-3.6.8/Py368ReadMe.txt

Currently build support is enabled using VS2019 and GCC5 tool chains for x86 and x64 bit platforms.
"""""""""

**To Reproduce**
open the page https://www.python.org/download/other/ 

**Expected behavior**
The page shall provide details of the C-Python port for UEFI shell.

**Screenshots**
NA

**Desktop (please complete the following information):**
 Not specific to browser

**Smartphone (please complete the following information):**
Not specific to device

**Additional context**
Adding a detailed discussion thread in the Python Core Development forum for your reference.
https://discuss.python.org/t/cpython-port-for-uefi-shell/23865

**Comment by jpshivakavi** [comment]
This request is similar to https://github.com/python/pythondotorg/issues/1523. 
The other download info needs to be updated with the Python for UEFI environment information as provided in this issue.

**Comment by jpshivakavi** [comment]
@ned-deily looks like you helped on #1523, could you see if you can help on this request as well.
It's simple update to the "other download" section of the page.

**Comment by ned-deily** [comment]
Thanks for the suggestion. The information has been added [here](https://www.python.org/download/other/).

**Comment by jpshivakavi** [comment]
Thanks @ned-deily for the quick turnaround time on this. Appreciate the help.
