### ISSUE TITLE
'Februaryr' Typo in Python Documentation by Version page

### ISSUE THREAD

**Issue by tobiasjcat** [proevo/pythondotorg#2255]
**Describe the bug**
In the "Python Documentation by Version" page, version 3.10.10 is listed as being released on 8 `Februaryr` 2023

**To Reproduce**
Go to [Python Documentation by Version](https://www.python.org/doc/versions/)

**Expected behavior**
`Februaryr` should be spelled `February`

**Comment by Mariatta** [comment]
Thanks for the report. This has been fixed now.
