### ISSUE TITLE
developer doc make serve command

### ISSUE THREAD

**Issue by vignesh7056** [proevo/pythondotorg#2257]
weblink for documentation - https://pythondotorg.readthedocs.io/install.html#getting-started
"make serve" command in developer doc is not working
docker & docker compose working properly

![pydocker issue](https://user-images.githubusercontent.com/37074210/223486532-29648bfa-7e34-4cc6-8736-cc843dc7b6ca.png)

**Comment by vignesh7056** [comment]
fixed using "docker compose up"

created a pull request "install.md documentation edited #2258"   with edited document.

**Comment by ambv** [comment]
Sounds like what you want is to [install `make` on Windows](https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows).
