### ISSUE TITLE
Possible hardcoded password: 'its-a-secret-to-everybody'

### ISSUE THREAD

**Issue by vignesh7056** [proevo/pythondotorg#2260]
pydotorg/settings/base.py

SECRET_KEY = 'its-a-secret-to-everybody'

**Comment by TrapiCaljpeezie** [comment]
> pydotorg/settings/base.py
> 
> SECRET_KEY = 'its-a-secret-to-everybody'

**Comment by hugovk** [comment]
@vignesh7056 This is just a placeholder, the real key is read from config:

https://github.com/search?q=repo%3Apython%2Fpythondotorg%20SECRET_KEY&type=code

You may close this issue.

@TrapiCaljpeezie Please don't spam.

**Comment by vignesh7056** [comment]
Ok.
