### ISSUE TITLE
Avoid assignments in operands

### ISSUE THREAD

**Issue by vignesh7056** [proevo/pythondotorg#2262]
static/js/plugins.js

`e+'direction-nav"><li><a class="'+e+'prev" href="#">'+c.prevText+'</a></li><li><a class="'+e+'next" href="#">'+c.nextText+"</a></li></ul>");a.controlsContainer?(d(a.controlsContainer).append(b),a.directionNav=d("."+e+"direction-nav li a",a.controlsContainer)):(a.append(b),a.directionNav=d("."+e+"direction-nav li a",a));f.directionNav.update();a.directionNav.bind(u,function(b){b.preventDefault();b=d(this).hasClass(e+"next")?a.getTarget("next"):a.getTarget("prev");a.flexAnimate(b,c.pauseOnAction)});`

Avoid assignments in operands; this can make code more complicated and harder to read. This is sometime indicative of the bug where the assignment operator '=' was used instead of the equality operator '=='.

**Comment by sahanasurapureddy** [comment]
can I work on this, could you assign it to me please?

**Comment by hugovk** [comment]
As mentioned in the other issue, we don't usually assign issues.

In this case, it's not entirely clear what the suggestion is. And https://github.com/python/pythondotorg/blob/main/static/js/plugins.js contains minimised, vendored JS code, so I doubt we want to modify that directly unless there's an actual demonstrable bug. And if there is, it should ideally be reported/fixed upstream first. 

Therefore I think this issue should be closed.

**Comment by vignesh7056** [comment]
ok
