### ISSUE TITLE
unused import in sourcecode

### ISSUE THREAD

**Issue by vignesh7056** [proevo/pythondotorg#2264]
downloads/tests/test_views.py

`from rest_framework.authtoken.models import Token`

this is an unused import can be removed

**Comment by Anuraag-CH** [comment]
I remove it and pushed the code and opened a pull request.Could you guide me as to run any tests.

**Comment by vignesh7056** [comment]
ok give me the pr link

**Comment by vignesh7056** [comment]
its a good practise to give a description for pull request. in this case " refactored source code by removing un used import belongs to "x" module to reduce the technical debt and increase readability of sourcce code."

**Comment by sahanasurapureddy** [comment]
Can I work on this issue, if its not resolved it yet?

**Comment by hugovk** [comment]
There's already a PR at https://github.com/python/pythondotorg/pull/2272

**Comment by hugovk** [comment]
Fixed by https://github.com/python/pythondotorg/pull/2272.
