### ISSUE TITLE
unused import in sourcecode

### ISSUE THREAD

**Issue by vignesh7056** [proevo/pythondotorg#2265]
jobs/migrations/0013_auto_20170810_1625.py

`from django.db import models, migrations`

this is an unused import can be removed.

**Comment by Saimanohar9999** [comment]
Is the above issue resolved????

**Comment by JacobCoffee** [comment]
There are lots of these but they can be cleaned up by #2540 later! Thanks anyways :) Check out https://github.com/python/pythondotorg/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3Ahelp-wanted for issues you can contribute to if interested
