### ISSUE TITLE
py3readiness.org is polluted in China

### ISSUE THREAD

**Issue by cheny0y0** [proevo/pythondotorg#2267]
**Describe the bug**
I went to ipaddress.com and looked up that the IPv4 addresses of py3readiness.org are 192.30.252.153 and 192.30.252.154. But when I `ping py3readiness.org`(using DNS 8.8.8.8), it resolves the domain to 75.2.37.224(Title: `电动志趣享` URL: `https://112a73c207f15de3da4197372017d598.parkingchina.diandongzhi.com/?acct=144&site=cHkzcmVhZGluZXNzLm9yZw==`)

**To Reproduce**
Just use a web browser and access py3readiness.org.

**Expected behavior**
Show the content like [Python 2.7 Readiness](https://pyreadiness.org/2.7/).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS Independent
 - Using Ping

**Additional context**
The link is under [Sunsetting Python 2 | Python.org](https://www.python.org/doc/sunset-python-2/).  
I'm also going to report this bug to [\@di](https://github.com/di)

**Comment by Mariatta** [comment]
Thanks for the report. I confirmed that the URL is bad.  I don't know who actually maintains the py3readiness.org. Perhaps we should just remove it from the text.

**Comment by OttomanZ** [comment]
@cheny0y0 perhaps try using `ProtonVPN` to see if it is reproduceable?

**Comment by cheny0y0** [comment]
> @cheny0y0 perhaps try using `ProtonVPN` to see if it is reproduceable? 
> 
> 
> 
> 

@OttomanZ No, it's not about accessibility or GFW(aka FangHuo ChangCheng). The correct IP address of py3readiness.org is accessible and can be successfully pingged. But it says “There isn't a GitHub Pages site here.”

Therefore I think it is hosted on GitHub.

**Comment by OttomanZ** [comment]
@cheny0y0 Yeah you should see their Page hosted on GitHub, as far as I have heard the Internet Firewall of China is notorious. Great you figured it out, but I would still recommend using a VPN if you're in China.

**Comment by hugovk** [comment]
In Europe, http://py3readiness.org/ shows a holding page because the site is no longer maintained (its repo is at https://github.com/chhantyal/py3readiness). So wherever you are in the world, the site is unavailable.

<details>
<summary>Screenshot</summary>


<img width="719" alt="image" src="https://github.com/python/pythondotorg/assets/1324225/e7e64aa4-e3aa-478d-a86f-1537a366c84e">

</details>

In any case, that website was made by a third-party, so all we can do is remove its link from https://www.python.org/doc/sunset-python-2/

**Comment by hugovk** [comment]
I've edited https://www.python.org/doc/sunset-python-2/ to replace the two occurences of http://py3readiness.org/ with https://web.archive.org/web/20190910095247/https://py3readiness.org/, an archive from around the time the sunset page was created (September 2019).

@cheny0y0 Please can you close this issue?

**Comment by cheny0y0** [comment]
> I've edited https://www.python.org/doc/sunset-python-2/ to replace the two occurences of http://py3readiness.org/ with https://web.archive.org/web/20190910095247/https://py3readiness.org/, an archive from around the time the sunset page was created (September 2019).
> 
> 
> 
> @cheny0y0 Please can you close this issue?

Copy that.
