### ISSUE TITLE
docs.python.org is now being polluted in China

### ISSUE THREAD

**Issue by cheny0y0** [proevo/pythondotorg#2273]
**Describe the bug**
Cannot access and ping `docs.python.org` in China using the default DNS.

**To Reproduce**
```
$ ping docs.python.org
PING docs.python.org (146.75.28.223) 56(84) bytes of data.
^\0/100 packets, 100% loss
```

**Expected behavior**
Can be pingged successfully.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux 5.19]
 - Browser: None

**Additional context**
BTW, I can found docs.python.org through Bing.

**Comment by khushi-98** [comment]
If you're experiencing difficulties accessing and pinging docs.python.org from China using the default DNS, it's possible that the website is being blocked by the Great Firewall of China (GFW). This firewall typically restricts access to specific websites and content that the Chinese government considers inappropriate or sensitive.

**Comment by ezio-melotti** [comment]
@ewdurbin, is there anything that can be done to solve this?

I think at some point https://www.python.org/downloads/ used to have a 下载 link to allow people behind the Great Firewall to download Python, so there might an existing solution that is already being used elsewhere.

**Comment by ewdurbin** [comment]
I don't have any definitive answer to what can be done in this situation, but if one is presented I'm happy to help implement it.

**Comment by hugovk** [comment]
Looking at the [visitor stats for docs.python.org](https://plausible.io/docs.python.org?period=30d&keybindHint=T), China accounts for the third-most visits (over the last 30 days):

![image](https://github.com/user-attachments/assets/8e3bbf0b-01e4-4992-8926-f72a1af54b1a)

**Comment by JacobCoffee** [comment]
If we are talking about downloads, will https://www.python.org/getit/ work? Done in #427 and mentioned in https://softwareengineering.stackexchange.com/a/213862

If so maybe this can be closed? Also this was originally for docs, which we have other repos for like https://docs.python.org/zh-cn/3/ or https://github.com/python/cpython/tree/main/Doc. 

I'm going to close this as it is quite old and it relates to another repo, but please reopen if you feel my answers aren't adequate - happy to help however we can!
