### ISSUE TITLE
site search doesn't find anything 

### ISSUE THREAD

**Issue by CarlFK** [proevo/pythondotorg#2277]
https://www.python.org/search/?q=MicroPython&submit=
"No results found."

Expected: 
[MicroPython](http://micropython.org/) (Python running on micro controllers)
https://www.python.org/download/alternatives/

https://www.python.org/search/ has 2 boxes.
Nothing I put into either search finds anything.  (result is always "No results found.")

**Comment by Mariatta** [comment]
Just tried to search for "PyCon" and I'm also getting "no search found" 😕

**Comment by darjeeling** [comment]
IMHO haystack backend is broken. maybe ES?

**Comment by khushi-98** [comment]
Hello,
Upon accessing the hyperlink, the results were readily available. However, there appears to be a server issue that may require further investigation. Nonetheless, the system is functioning appropriately otherwise.

**Comment by CarlFK** [comment]
searching for "MicroPython" and "PyCon" return results.  looks good.
