### ISSUE TITLE
Python 3.10.12 release notes incorrectly mention Python 3.8

### ISSUE THREAD

**Issue by edmorley** [proevo/pythondotorg#2280]
**Describe the bug**
The [Python 3.10.12 release notes](https://www.python.org/downloads/release/python-31012/) mention Python 3.8 at the end (under the "No installers" section), which is presumably a copy paste leftover.

**To Reproduce**
1. Go to https://www.python.org/downloads/release/python-31012/
2. Use find in page for the phrase "Python 3.8"

**Expected behavior**
No references to Python 3.8 on that page, since the page is for Python 3.10.x.

**Screenshots**
<img width="1005" alt="Screenshot 2023-06-07 at 07 47 11" src="https://github.com/python/pythondotorg/assets/501702/a354117f-d10d-44ca-aa2e-9fb08c1ad815">

**Comment by ned-deily** [comment]
Thanks for the heads-up, now fixed!

**Comment by edmorley** [comment]
Thank you :-)
