### ISSUE TITLE
Sigstore documentation doesn't have example for `.sigstore` bundles

### ISSUE THREAD

**Issue by sethmlarson** [proevo/pythondotorg#2285]
**Describe the bug**

Follow-up from #2247, the examples on the Sigstore information page (https://python.org/download/sigstore) only references being able to verify `.crt` and `.sig` files, where now new releases have a singular Sigstore bundle file `.sigstore` that should be verified with `--bundle <FILE>`.

Since there are releases out there with both flavors of verification material, we'll need to give the user instructions on which method to use based on which materials are available.

I was going to make the contribution to fix this myself, but I was unable to grep the `Sigstore Information` page header anywhere in this project or under the `python` org in GitHub. Maybe my search skills or GitHub is failing here somehow, but where is the source code for the page in question?

**Comment by woodruffw** [comment]
Thanks for pinging me downstream! Adding an example of verifying using `--bundle` seems exactly appropriate to me.

> Maybe my search skills or GitHub is failing here somehow, but where is the source code for the page in question?

I think I ran into the same thing -- I believe it's in a CMS somewhere, and @di has modified it in the past.

**Comment by di** [comment]
It is indeed in the python.org CMS, which I have edit access to.

**Comment by ned-deily** [comment]
There probably should also be refereences to sigstore on the [Python Downloads page](https://www.python.org/downloads/). I've opened [a new issue](https://github.com/python/pythondotorg/issues/2299) about that.

**Comment by sethmlarson** [comment]
As a part of this work I'd like to backfill the existing crt/sig files with bundles for easier verification instructions. @woodruffw and I created this issue to track this functionality in sigstore-python: https://github.com/sigstore/sigstore-python/issues/718

**Comment by sethmlarson** [comment]
Created a task for back-filling Python releases from existing verification materials: https://github.com/python/pythondotorg/issues/2300

**Comment by sethmlarson** [comment]
Once bundles have been [backfilled](https://github.com/python/pythondotorg/issues/2300) and the documentation updated we can remove the crt/sig generation from python/release-tools to match the default generation behavior from [sigstore-python v2](https://github.com/sigstore/sigstore-python/issues/771#issuecomment-1716216958).

**Comment by sethmlarson** [comment]
Releases have been backfilled with bundles so I've updated [the documentation](https://www.python.org/download/sigstore/) to only reference verifying Sigstore bundles. We can now close this issue.
