### ISSUE TITLE
HTTPS certificate for https://python.org only valid for `c.shared-424-default.ssl.fastly.net`

### ISSUE THREAD

**Issue by ds-cbo** [proevo/pythondotorg#2286]
**Describe the bug**

When trying to visit https://python.org, a certificate warning is shown about the certificate only being valid for `c.shared-424-default.ssl.fastly.net`.

**To Reproduce**

1. Go to https://python.org/

**Expected behavior**

Right certificate is used, same page as https://www.python.org/ is shown

**Screenshots**
<img width="955" alt="image" src="https://github.com/python/pythondotorg/assets/82801887/3fd37bfb-fc63-454b-af10-28f3da2353d2">

<img width="880" alt="image" src="https://github.com/python/pythondotorg/assets/82801887/139ab1d2-7bbe-4419-b0c8-fbc21ded20d0">

**Desktop**
 - OS: macOS
 - Browser Firefox
 - Version 114.0.2

**Additional context**

I am visiting from the Netherlands

https://www.python.org/ works fine, and http://python.org redirects to it so also works fine

**Comment by hugovk** [comment]
Note: GitHub has tried to be helpful and shows both `https://python.org` and `https://www.python.org` as `python.org`.

For example here's no www: https://python.org and here's with www: https://www.python.org

So check carefully what the links actually are in the report above :)

---

When I go to `https://python.org` (no www), it now redirects to `https://www.python.org` (with www) and the certificate looks okay there:

![image](https://github.com/user-attachments/assets/5dcad433-5099-4c8b-a348-9e7d9677d2cf)

@ds-cbo Does it work for you too, and please can you close this issue if so? Thanks!

**Comment by ds-cbo** [comment]
@hugovk I cannot reproduce the issue anymore, I think it's already fixed in the meantime. Thanks for your response anyway.
