### ISSUE TITLE
Add element ids to headings to allow direclty links (at least on the CoC page)

### ISSUE THREAD

**Issue by CAM-Gerlach** [proevo/pythondotorg#2287]
**Is your feature request related to a problem? Please describe.**

We would like to link to the section "PSF Online spaces" on the [Code of Conduct page](https://www.python.org/psf/conduct/) to specifically disambiguate what is meant by the CoC applying to, and enforcing bans from, "core dev spaces". However, that is not possible, as the headings on that page (and I'm presuming others, based on spot-checks) lack element ids that could be used a URI fragment.

**Describe the solution you'd like**

Ideally, ensure all headings `<hN>` get automatically generated, unique, stable and linkable element ids, as is done on most other websites including the Python docs, etc.

**Describe alternatives you've considered**

Alternatively, as a more immediate solution to the proximate issue, have a subpage under the code of conduct section that explicitly (re) enumerates the spaces in question, that could be linked to as a top-level page.

**Additional context**

This is the specific section in question, FWIW"

![image](https://github.com/python/pythondotorg/assets/17051931/22049aec-d46a-491e-a693-f834bfbc0fae)

**Comment by NateKoehler** [comment]
I'll be working on this!

**Comment by lena6zp** [comment]
Hi @CAM-Gerlach, may I have an example of the Python docs you mentioned that has a unique id for headings？ Also, I had a hard time finding the source code of the [Code of Conduct page]. Do you know if it is accessible to the public? 
Thank you!

**Comment by CAM-Gerlach** [comment]
> Hi @CAM-Gerlach, may I have an example of the Python docs you mentioned that has a unique id for headings？

[Here's one example](https://docs.python.org/3/tutorial/controlflow.html#keyword-arguments)

> Also, I had a hard time finding the source code of the [Code of Conduct page]. Do you know if it is accessible to the public?

I'm not really familiar at all with this site's codebase, but my guess would be that it's stored in the deployed CMS rather than statically in the source of this repo. But I presume the code changes would be to the code that generates the page HTML, and/or the HTML templates, rather than anything specific to that page's content. Sorry I couldn't point you in a more specific direction, you'd have to ask Ee or someone else with more experience with this particular codebase.

**Comment by NateKoehler** [comment]
Hi, @ewdurbin Would you be able to give us insight on a good starting point or if we need additional access to the source files in order to edit the Code of Conduct webpages.
Thanks!

**Comment by lena6zp** [comment]
> > Hi @CAM-Gerlach, may I have an example of the Python docs you mentioned that has a unique id for headings？
> 
> [Here's one example](https://docs.python.org/3/tutorial/controlflow.html#keyword-arguments)
> 
> > Also, I had a hard time finding the source code of the [Code of Conduct page]. Do you know if it is accessible to the public?
> 
> I'm not really familiar at all with this site's codebase, but my guess would be that it's stored in the deployed CMS rather than statically in the source of this repo. But I presume the code changes would be to the code that generates the page HTML, and/or the HTML templates, rather than anything specific to that page's content. Sorry I couldn't point you in a more specific direction, you'd have to ask Ee or someone else with more experience with this particular codebase.

Thank you for the example!

**Comment by ewdurbin** [comment]
I think this would be best accomplished by adding it as a feature of the renderer to add ids to headings rather than editing the contents page by page.

That would probably be done by adding a step in the [page views](https://github.com/python/pythondotorg/blob/main/pages/views.py) after rendering the page contents using beautifulsoup which is already available as a dependency.

**Comment by NateKoehler** [comment]
Thank you for your time @ewdurbin, maybe you can access more information than myself or my teammates can. It seems the code of conduct page and other pages within the psf and community are returning a 404 error within the local/virtual environment. If requesting the url "/psf/conduct", such as on the production/live website where you would find the code of conduct, you will be directed to a 404 error. We assume this is the cause of some of the templates being stored in a different database where we are unable to access.

**Comment by CAM-Gerlach** [comment]
> That would probably be done by adding a step in the [page views](https://github.com/python/pythondotorg/blob/main/pages/views.py?rgh-link-date=2023-10-09T12%3A42%3A47Z) after rendering the page contents using beautifulsoup which is already available as a dependency.

Ah, great, thanks! That should point @NateKoehler and @lena6zp in the right direction.

> Thank you for your time @ewdurbin, maybe you can access more information than myself or my teammates can. 

Well, yes, because they are the admin of the website and the PSF infrastructure :) But this shouldn't really affect your ability to test the change, since it will presumably be in or near the file in this repo that @ewdurbin mentioned above.

> It seems the code of conduct page and other pages within the psf and community are returning a 404 error within the local/virtual environment. If requesting the url "/psf/conduct", such as on the production/live website where you would find the code of conduct, you will be directed to a 404 error. We assume this is the cause of some of the templates being stored in a different database where we are unable to access.

Yes; as @ewdurbin and I have both explained to you, this repo is the backend for the CMS running the PSF site, and doesn't contain the specific page content, but that is shouldn't be necessary to solve this issue, since instead it should be fixed properly in the CMS instead of just trying to hack something manually into one specific page. 

I'm assuming you could just use the CMS to create a sample page with headings, and test your solution on that? And/or write some unit tests for it? Or perhaps there's a built-in example somewhere?

**Comment by hugovk** [comment]
The code of conduct pages and other policies have been moved to their own website at https://policies.python.org (repo: https://github.com/psf/policies/).

This means the "PSF Online spaces" section is now linkable:

https://policies.python.org/python.org/code-of-conduct/#psf-online-spaces

Is there anything more to do here, or can this issue be closed?
