### ISSUE TITLE
Idea for Python

### ISSUE THREAD

**Issue by ghost** [proevo/pythondotorg#2291]
Hello! I am Aditeyo. I am a beginner of Python programming. But, I have a idea to make Python more advanced. So the idea is that -

There should be a section called *Runing Map*. After making your code, you can see how the code is working. Like a detailed Flow-Chat. It should generate it fast. And It can help the developer. So the developer can understand or see if the code is working the way he wanted. 

Thank you!

- Aditeyo Ghosal

**Comment by Jangle-Parth** [comment]
Hello Aditeyo,

Your idea of a "Running Map" for Python is valuable! There's a fantastic tool called [Python Tutor](https://pythontutor.com/python-compiler.html#mode=edit) that already offers code visualization to help developers understand and debug their code better. It's a great resource to enhance your Python programming skills.

Best regards,
Jangle Parth

**Comment by JacobCoffee** [comment]
Related issues to CPython should be opened here: https://github.com/python/cpython/ but probably discussed first at https://discuss.python.org/
