### ISSUE TITLE
Changing URL

### ISSUE THREAD

**Issue by josiedjong** [proevo/pythondotorg#2292]
I noticed that there is a reference to LEQUAL's website on this page: https://www.python.org/success-stories/python-seo-link-analyzer/

However, the link refers to an old page, namely: https://www.lequal.nl/diensten/zoekmachine-optimalisatie/

It would be ideal for both us and your visitors if the link could refer to the new page, namely: https://www.lequal.com/nl/

**Comment by mwichmann** [comment]
Sorry there's been no response - I know you emailed webmaster@python.org about this earlier, but we couldn't get anything done either.

**Comment by mwichmann** [comment]
As a thought, if you change your website, perhaps you could add a redirect for the old page?

**Comment by coderanger** [comment]
The link has been updated, thanks!
