### ISSUE TITLE
File not found when looking for a python t-shirt

### ISSUE THREAD

**Issue by Nekyt** [proevo/pythondotorg#2294]
**Describe the bug**
When I visit the community tab of the python website, and then click on Python T-Shirts and other merchandise, I get file not found.

**To Reproduce**
1. Go to Community tab in the top bar of the website
2. Click on "Community"
3. Scroll down to [Python T-Shirts and other merchandise](https://www.python.org/community/merchandise/)

**Expected behavior**
Awesome t-shirts page to support the awesome Python software foundation.

**Comment by darshanc4696** [comment]
Hi Nekyt ,
The problem mentioned by you was "file not found" error. This is because the search for "Python T-shirts and other merchandise" is not found in the community page. The button or link to "T-shirts or merchandise" is not found in that page. So, the button/link that doesn't exist in the community page and when you search for it , you get an "file not found" error.
Just check the community page once.

**Comment by hugovk** [comment]
In other words, this issue should now be closed because it has been fixed/cannot be reproduced.

> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to Community tab in the top bar of the website
> 2. Click on "Community"
> 3. Scroll down to [Python T-Shirts and other merchandise](https://www.python.org/community/merchandise/)

There's no longer any t-shirt or merchandise links on https://www.python.org/community/

**Comment by Nekyt** [comment]
I still am able to reproduce the issue.
The url for the page is https://www.python.org/community-landing/
To get to this page you first need to click on community from the top bar after just visiting python.org
![image](https://github.com/python/pythondotorg/assets/31213138/6249029a-9b82-4383-90c1-e5db387890dd)
Then you have to scroll until you find this link
![image](https://github.com/python/pythondotorg/assets/31213138/e382c93c-f26f-44b4-988a-c0dc9f737204)
After you click on it you land on:
![image](https://github.com/python/pythondotorg/assets/31213138/4b63857b-75ef-406e-ad7f-8f809e8818c8)

**Comment by hugovk** [comment]
Aha, thanks.

Perhaps we should have both these Community tabs link to https://www.python.org/community/ ?

And have https://www.python.org/community-landing/ redirect to https://www.python.org/community/ ?

![image](https://github.com/python/pythondotorg/assets/1324225/e1d8cd86-580b-4481-94d5-9e6bb64b87f8)

**Comment by dorian-adams** [comment]
I was unable to recreate this issue locally. Both community tabs properly link to '/community/'. Additionally, I searched through the project, including its fixtures, and could not find '/community-landing/' used anywhere. So I suspect this is something that needs to be corrected within the production cms. Nonetheless, I opened a PR that adds an appropriate 301.

Please let me know if there is anything else I should include. Thanks!
