### ISSUE TITLE
Belarusian language

### ISSUE THREAD

**Issue by 1QMIK** [proevo/pythondotorg#2303]
Belarusian language at this page: https://wiki.python.org/moin/Languages
Shows as "BelorussianLanguage", but should be "BelarusianLanguage" with a and 1 s

**Comment by Eclips4** [comment]
Hi!
Where did you see this? I see only `BelarusianLanguage`

**Comment by hugovk** [comment]
Thanks to @malemburg for fixing it yesterday:

https://wiki.python.org/moin/Languages?action=diff&rev2=77&rev1=76

https://wiki.python.org/moin/BelarusianLanguage?action=info

This issue can be closed now.
