### ISSUE TITLE
GPG signature for python 3.12 Gzipped source tarball is missing

### ISSUE THREAD

**Issue by mayeut** [proevo/pythondotorg#2308]
**Describe the bug**
GPG signature for python 3.12 Gzipped source tarball is missing

**To Reproduce**
1. Go to https://www.python.org/downloads/release/python-3120rc2/
3. Scroll down to 'Files'
4. You can observe the GPG signature for the Gzipped source tarball is missing

**Expected behavior**
GPG signature for python 3.12 Gzipped source tarball is available

**Screenshots**
<img width="1162" alt="image" src="https://github.com/python/pythondotorg/assets/9768336/e93be590-60ca-439c-932a-e28cb1296dc9">

**Comment by hugovk** [comment]
cc @Yhg1s @sethmlarson

**Comment by sethmlarson** [comment]
Thanks for submitting this issue, I'll follow up with Thomas.

**Comment by Yhg1s** [comment]
It should be fixed. Something went wrong with the original GPG signing of the tgz, and the release process doesn't actually check that they succeed (it uses os.system to call gpg). I've verified the integrity of the archive and signed it.

**Comment by mayeut** [comment]
I can confirm this is fixed. Thanks.
