### ISSUE TITLE
Why the python download website does not have a linux binary excutable download link?

### ISSUE THREAD

**Issue by yingshaoxo** [proevo/pythondotorg#2310]
## Node.js have it on their website home page:

![image](https://github.com/python/pythondotorg/assets/17190829/37886953-2c49-4799-9a0b-fde2dc2ced86)

## But python does not have it:
![image](https://github.com/python/pythondotorg/assets/17190829/b7f358c1-7ba4-4ba7-8a4d-4d73048a0849)

## **No wonder applications that based on javascript syntax is everywhere noadays, because it is so easy to use!**

**Comment by yingshaoxo** [comment]
Even Java has linux binary download, why python do not have it?:

![image](https://github.com/python/pythondotorg/assets/17190829/f6a62099-9f35-40a3-8b89-441a76843d57)

https://www.oracle.com/java/technologies/downloads/

**Comment by mags0ft** [comment]
I also don't want to download any binaries from apt repositories called "deadsnakes" or similar... what is going on, why aren't there any official binaries? Compiling it by yourself everytime can't be the option!

**Comment by hugovk** [comment]
Please join the discussion at https://discuss.python.org/t/publish-linux-installer-on-python-org/53760.
