### ISSUE TITLE
TEST CASE FAILURE

### ISSUE THREAD

**Issue by Shashinoor13** [proevo/pythondotorg#2312]
I ran tests on my local device and two test cases were failing.
1.test_mmap
2.test_urllib2_localnet

**Comment by hugovk** [comment]
There are no such tests in this repo, you want https://github.com/python/cpython.

Please close this issue, and if you open a new one:

* Don't use all capitals for the title and make it more descriptive.
* Tell us what Python and OS version you're using.
* What commands you ran.
* The full output of the errors.
