### ISSUE TITLE
Add r/Python links to the community pages

### ISSUE THREAD

**Issue by JacobCoffee** [proevo/pythondotorg#2313]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
No issue, just a new request

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. It would be great if [...]

- Add [r/Python](https://www.reddit.com/r/Python/) to the forum listing on the https://www.python.org/community/forums/
- Add [r/Python](https://www.reddit.com/r/Python/) to the community listing on https://www.python.org/community/

**Describe alternatives you've considered**

**Additional context**

[r/Python](https://www.reddit.com/r/Python/) is a very large Python community on Reddit that I help manage.
The current forum page lists [r/LearnPython](https://www.reddit.com/r/LearnPython/) as a place community members can go, and it would make sense to add [r/Python](https://www.reddit.com/r/Python/) there as well.

In addition, with the size and scope of the [r/Python](https://www.reddit.com/r/Python/) community, I believe that it rivals that of the Python Discord in terms of engagement and users. Part of me would like to see this community on the main community (https://www.python.org/community/) page. I could see that being not desirable as well, though. So sort've up to you all.

I am more than happy to do this work and any other changes needed done - but I am unsure of where this exists. I think @hugovk mentioned it lives in a CMS DB somewhere, but either way.. let me know if I can help contribute :)
```[tasklist]
### Tasks
- [ ] Add r/Python to the forum listing on the python.org/community/forums
- [ ] Add r/Python to the community listing on python.org/community
```

**Comment by iamtiagogalvao** [comment]
@JacobCoffee, firstly, thank you for raising this point. Your commitment to r/Python is commendable.

You've pointed out the absence of r/Python from the [python.org/community/forums/](https://www.python.org/community/forums/) and [python.org/community/](https://www.python.org/community/) listings. Given the size and vitality of the r/Python community, I concur with your suggestion.

Considering your statement and the precedent of listing r/LearnPython, the inclusion of r/Python seems both relevant and timely.

I hope that the team accepts this request.

**Comment by hugovk** [comment]
I've added [r/Python](https://www.reddit.com/r/Python/) to https://www.python.org/community/forums/

**Comment by JacobCoffee** [comment]
Thanks!
