### ISSUE TITLE
blog for py 3.11.6 has download link to 3.11.0

### ISSUE THREAD

**Issue by thezoggy** [proevo/pythondotorg#2314]
**Describe the bug**
blog for py 3.11.6 has download link to 3.11.0

**To Reproduce**
1. Go to https://pythoninsider.blogspot.com/2023/10/python-3116-is-now-available.html
2. The page shows link "https://www.python.org/downloads/release/python-3116/" but links to 3110

**Expected behavior**
url should reflect correct link

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 118.01

**Additional context**
Also reported via irc

**Comment by pablogsal** [comment]
Thanks for the heads up. I have fixed the link 👍
