### ISSUE TITLE
Update footer links

### ISSUE THREAD

**Issue by hugovk** [proevo/pythondotorg#2317]
A couple of the links in the footer need updating:

# PEP Index

http://python.org/dev/peps/ -> https://peps.python.org

# Issue Tracker

https://bugs.python.org/ -> https://devguide.python.org/triage/issue-tracker/ (or https://github.com/python/cpython/issues)

**Comment by buddhiraz** [comment]
Hey @hugovk , 

is the issue open yet ? if finish please close this.

Thanks.

**Comment by hugovk** [comment]
It's still open, we're waiting for https://github.com/python/pythondotorg/pull/2318 to be merged.
