### ISSUE TITLE
Link to the official Python Software Foundation (PSF) Mastodon account is broken

### ISSUE THREAD

**Issue by mlcohen** [proevo/pythondotorg#2321]
The Python Software Foundation (PSF) news and community [web page](https://www.python.org/psf/news-and-community/) has a link to the official [PSF Mastodon account](https://fosstodon.org/@ThePSF). The link should navigate the user to `https://fosstodon.org/@ThePSF` but instead redirects the user to `https://fosstodon.org/@ThePSF>` which ends up showing a 404 page on fosstodon.org. This is reproducible on Chrome, Safari and Firefox.

OS: macOS Ventura 13.6
Safari: v17
Chrome: 119.0.6045.123
Firefox: 119.0.1

<img width="1351" alt="Screenshot 2023-11-10 at 10 25 52 PM" src="https://github.com/python/pythondotorg/assets/100445/ec01850e-2d21-4a53-bcf7-846f4b4344b1">

<img width="1012" alt="Screenshot 2023-11-10 at 10 35 33 PM" src="https://github.com/python/pythondotorg/assets/100445/062cc869-25e8-454f-a6b4-0b7964baa753">

**Comment by joncle** [comment]
This has been updated - thanks.

**Comment by mlcohen** [comment]
Verified that the link now works. Thank you!
