### ISSUE TITLE
Include a link to official PSF Mastodon account in the Python.org socialize menu

### ISSUE THREAD

**Issue by mlcohen** [proevo/pythondotorg#2322]
The socialize menu on python.org has prominent links to the Python Software Foundation's (PSF) Facebook, Twitter and IRC official social accounts. Recommend updating the menu to include a link to the [official PSF Mastodon account](https://fosstodon.org/@ThePSF). 

The Mastodon PSF account has well over 9,000 followers. For those who would like to get PSF updates via social media but not follow on Twitter/X and/or Facebook, [Mastodon](https://joinmastodon.org) is a great alternative. Without a prominent  link to the Mastodon account on python.org, many may not even know that Mastodon was ever an option.

<img width="1351" alt="Screenshot 2023-11-11 at 1 23 02 PM" src="https://github.com/python/pythondotorg/assets/100445/bc97e1d7-9e5c-4191-a30a-6af5b8277018">

**Comment by hugovk** [comment]
Here's where to add it (before Twitter ;)

https://github.com/python/pythondotorg/blob/c4ee749942227ca75c8e670546afe67232d647b2/templates/base.html#L236-L241

But I'm less clear how to update the styles/custom font to add the icon via `class="icon-mastodon"`.

**Comment by mlcohen** [comment]
> I'm less clear how to update the styles/custom font

I took a crack at it using [IcoMoon](https://icomoon.io). Was able to get a Mastodon icon added and generate a collection of fonts. Now working on updating the CSS.

<img width="1351" alt="Screenshot 2023-11-11 at 11 30 18 PM" src="https://github.com/python/pythondotorg/assets/100445/cde5938e-a794-464d-bc13-40fcd4ec1549">

**Comment by mlcohen** [comment]
Can confirm that the python.org website now has a prominently placed link to the official Python Software Foundation [Mastodon account](https://fosstodon.org/@ThePSF).

<img width="1415" alt="Screenshot 2023-11-14 at 9 01 56 AM" src="https://github.com/python/pythondotorg/assets/100445/a54047a8-fe37-48de-b96c-b3d1bcc204ed">
