### ISSUE TITLE
Modernise a modern language's website.

### ISSUE THREAD

**Issue by v-pun215** [proevo/pythondotorg#2326]
It would be cool if the website was simplified and it would be easy to download python with one click on the home page, and download other versions easily. I am a web dev and a python dev myself and I think the website is way too complicated for the average Joe. If thats too much work, then maybe I can contribute as well.

**Comment by JacobCoffee** [comment]
At this time we won't be doing any work like this - however it may come up in the future. There are some ideas I have around this as well. 

When the time comes, there will probably be a pinned issue or larger announcement so just stay tuned :)
