### ISSUE TITLE
This also affects reviewing; e.g. I wasn't able to reject https://www.python.org/jobs/189/ until I fixed a reST error in the job description field.

### ISSUE THREAD

**Issue by kajalagarwaljob378** [proevo/pythondotorg#2333]
This also affects reviewing; e.g. I wasn't able to reject https://www.python.org/jobs/189/ until I fixed a reST error in the job description field.

_Originally posted by @mjpieters in https://github.com/python/pythondotorg/issues/652#issuecomment-83984334_

**Comment by JacobCoffee** [comment]
Unsure if this still needs investigation after https://github.com/python/pythondotorg/issues/652 was closed

**Comment by hugovk** [comment]
This very much looks like a spammer: new account creating issue from another, not interacting with the original or at all after this.

Let's close, we can always reopen later.
