### ISSUE TITLE
Accounts payable email is wrong (?)

### ISSUE THREAD

**Issue by SnoopJ** [proevo/pythondotorg#2335]
**Describe the bug**
The email address listed for PSF accounts payable is `accounting@ptyhon.org`, which I am nearly sure is supposed to be `accounting@python.org`

I would have submitted this issue as a PR, but I cannot find the relevant souce in this repository. I suspect I'm missing a trick there.

**To Reproduce**
1. Go to https://www.python.org/psf/accounts-payable/
2. Click on `the PSF accounting team`
3. Note the provided email address

**Additional context**
Discovered while confirming the address before contacting it!

**Comment by joncle** [comment]
Typo fixed - thanks.
