### ISSUE TITLE
PEP 703: Clearly differentiate free-threaded installers from regular

### ISSUE THREAD

**Issue by hugovk** [proevo/pythondotorg#2336]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

As part of the [PEP 703 acceptance](https://discuss.python.org/t/pep-703-making-the-global-interpreter-lock-optional-in-cpython-acceptance/37075?u=hugovk), the steering council said it will be very important to get feedback from the community, but to carefully note early builds are experimental:

> Phase I: Experimental phase, which can start immediately, in which the free-threaded build is enabled through a build-time option. This should not be the default install anywhere. At least one major Python release should include this experimental free-threaded build, to allow third-party packages to test and do their own experimentation. In this stage we should make it clear the build is experimental, not supported for “production use”, and may be reverted.

We're not quite ready to distribute free-threaded installers, but when we are we'll need a way to share them.

The most obvious way is to include them in the release pages:

* https://www.python.org/downloads/release/python-3130a2/

But we need to make sure they're very clearly marked as experimental, and not just with an "Experimental" note like the Windows installer (ARM64).

Maybe in another table, or something completely different.

**Describe alternatives you've considered**

Not show them on these pages, but still have the binaries available, and we link to them from blog or Discourse posts, or from FTP listings. This might suffice for the current Phase I (Experimental), but I think we'll need listings for Phase II (Supported-but-not-default).

**Additional context**

See also https://github.com/python/pythondotorg/issues/2194, it seems many people install 32-bit Python on 64-bit Windows because 32-bit Python is first on the list and don't heed the "Recommended" note next to 64-bit Python.

**Comment by JacobCoffee** [comment]
Hi @hugovk is this still needed/wanted? I could work on this after I wrap up my migration work?

**Comment by hugovk** [comment]
Yes, I think it will still be needed at some point.

Although, we don't yet have any separate free-threaded installers for 3.13, and it's not entirely clear yet if we will for 3.13, or what form they will take.

Something semi-related that would be useful, implement some form of "feature releases" boxes at the top, similar to Node.js and Go here: https://github.com/python/pythondotorg/issues/2194#issuecomment-1874289095

**Comment by JacobCoffee** [comment]
That sounds good. Can you assign this to me? https://github.com/python/pythondotorg/issues/2419

**Comment by hugovk** [comment]
I don't have any merge or triage rights in this repo :) You [comment](https://github.com/python/pythondotorg/issues/2419#issuecomment-2010935090) is enough.

**Comment by hugovk** [comment]
Turns out this is not needed, in the end we added options to the existing macOS and Windows installers, rather than creating separate installers for free-threaded builds 👍 

* https://github.com/python/cpython/issues/112430
* macOS: https://github.com/python/cpython/issues/120098
* Windows: https://docs.python.org/3.13/using/windows.html#installing-free-threaded-binaries
