### ISSUE TITLE
Release notes on the download page for 3.12.0 go to an incorrect URL

### ISSUE THREAD

**Issue by dev-coder** [proevo/pythondotorg#2337]
**Describe the bug**
Release notes link on the download page (https://www.python.org/downloads/) for 3.12.0 goes to the wrong location. Should be going to: 
https://docs.python.org/release/3.12.0/whatsnew/changelog.html#python-3-12-0  (which works if you manually type it following the former versions by convention, but the link currently for the release notes is wrong and goes to: https://www.python.org/downloads/

**To Reproduce**
1. Go to 'https://www.python.org/downloads/'
2. Click on 'Specific Release table, 3.12.0, Release Notes hyperlink'
3. Goes to the download page you are already on, and NOT to the actual release notes.

**Expected behavior**
Clicking the 3.12.0 release notes should take you to: https://docs.python.org/release/3.12.0/whatsnew/changelog.html#python-3-12-0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hugovk** [comment]
Thanks for the report, cc @yhg1s.

**Comment by mattbaker-digital** [comment]
Same for 3.12.1

**Comment by JacobCoffee** [comment]
This seems to be fixed for both

<img width="1495" alt="image" src="https://github.com/user-attachments/assets/84ed81c8-65cf-462b-a5db-3181298f1326">
