### ISSUE TITLE
Display only benefits associated with the year of the sponsorship package being edited

### ISSUE THREAD

**Issue by loren-c** [proevo/pythondotorg#2342]
**Is your feature request related to a problem? Please describe.**
In python.org/admin/sponsors/sponsorship in the details page for a sponsorship under benefits, if you add or edit one of the benefits in the sponsorship, the dropdown menu shows every benefit from all years as options. This makes it difficult to find the right benefit and requires lots of scrolling.

**Describe the solution you'd like**
It would be great if only benefits associated with the same year as the sponsorship displayed as options. E.g. for a 2024 Sponsorship, you would only see benefits ending in  "(2024)" and not "(2023)" and "(2022)" 

**Additional context**
Screen recording of what it currently looks like here: https://github.com/python/pythondotorg/assets/93948470/713dc59c-7ace-4a98-88ca-7bc2d2081672

@ewdurbin

**Comment by ewdurbin** [comment]
@jessiebelle can you take a look at this specific issue as well as other places in the sponsorship admin where stuff like this is going on? please submit an individual PR for each change.
