### ISSUE TITLE
Remove or update https://www.python.org/psf/membership/sign/

### ISSUE THREAD

**Issue by dawnwages** [proevo/pythondotorg#2347]
**Describe the bug**
The information on Python Membership is outdated and does not align with primary page. 
Primary Page: https://www.python.org/psf/membership/
Incorrect/outdated page: https://www.python.org/psf/membership/sign/

The incorrect part of the page is the description of "Managing member" as "You qualify as a Managing Member if you dedicate at least five hours per month working to support the Python Software Foundation or the Python community--organizing Python events, working on PSF projects, participating in one of the PSF's working groups, etc." 

**To Reproduce**
It's floating around on search engines. https://www.python.org/psf/membership/sign/

**Expected behavior**
Updated information.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hugovk** [comment]
If removing https://www.python.org/psf/membership/sign/, I recommend adding a redirect to https://www.python.org/psf/membership/ so people who follow old links to the old one end up at the good one.

**Comment by indepndnt** [comment]
I have updated the content of this page to invite visitors to either go to our membership page or our membership FAQ and removed everything else. This issue can be closed.
