### ISSUE TITLE
Incorrect link on Fiscal Sponsors page

### ISSUE THREAD

**Issue by AmandaPerino** [proevo/pythondotorg#2357]
Page: https://www.python.org/psf/fiscal-sponsorees/
Section: Boston Python
Link: Mistakenly directs to Chicago Python User group. Should be: https://about.bostonpython.com/

**Comment by vaishnavi192** [comment]
hey @AmandaPerino I would like to take up this issue!  will create a pr soon

**Comment by vaishnavi192** [comment]
Hey @AmandaPerino I want to take up this issue. Do you have any idea where is the file related to this in codebase I am not able to find it

**Comment by AmandaPerino** [comment]
Hi @vaishnavi192 I'm afraid I was just a visitor to the site reporting a bug, I am not involved with the org itself. Hopefully someone who knows can weigh in for you here.

**Comment by The-Compiler** [comment]
I don't follow, for what it's worth. The "Boston Python" link there links to https://www.meetup.com/bostonpython/ which seems correct to me, no?

**Comment by vaishnavi192** [comment]
@The-Compiler he is saying that it should redirect to https://about.bostonpython.com/ this page. yes it links to https://www.meetup.com/bostonpython/ this page as of now and not some Chicago user grp page. Is this page fine then?

**Comment by AmandaPerino** [comment]
@The-Compiler Very strange, but indeed the link is correct now. Not sure whta went wrong. Probably a user fail. :) Sorry for the confuaion @vaishnavi192!
