### ISSUE TITLE
Add DearPyGui on home page under "Use Python for…" section

### ISSUE THREAD

**Issue by cfsok** [proevo/pythondotorg#2360]
[DearPyGui](https://pypi.org/project/dearpygui/) is an excellent GUI framework and I think it deserves to be listed in "Use Python for…" section of https://www.python.org/ (see below).

![image](https://github.com/python/pythondotorg/assets/33849525/ce0d12bb-cf84-497d-b73b-e3594c6116c4)

I am not sure how to do a PR for this.

**Comment by khushi-98** [comment]
Insert the following code in the GUI section  
a class="tag" href="https://pypi.org/project/dearpygui/">DearPyGui</a


![3](https://github.com/python/pythondotorg/assets/102850725/8983044f-9238-4cdb-aec0-65addf15bca6)

**Comment by khushi-98** [comment]
Hlo,
Can u plz tell me how did u create pull request?
@cfsok

**Comment by cfsok** [comment]
@khushi-98 I am sorry but do not understand the nature of your question. Are you looking for instructions, or are you suggesting I might have not followed the right process?

**Comment by khushi-98** [comment]
@cfsok I want to know how did you create a pull request. I would appreciate your guidance.

**Comment by cfsok** [comment]
@khushi-98 you can read this guide: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by khushi-98** [comment]
Can u tell me the path for pyhton website source code??
@cfsok

**Comment by cfsok** [comment]
@khushi-98 The website source code is in this repo, but I do not have an understanding of its structure to help you further. I simply did a search to find the part of interest in my case.

**Comment by khushi-98** [comment]
@cfsok Can u mention the repo here? It will be helpful to me.
