### ISSUE TITLE
Success Stories submission form - Add help text requesting Markdown formatting to the Content box

### ISSUE THREAD

**Issue by loren-c** [proevo/pythondotorg#2364]
**Is your feature request related to a problem? Please describe.**
When users use [the Success Stories submission form](https://www.python.org/success-stories/create/) to submit a success story, there is currently no guidance on whether to submit Success Stories in plain text or a mark up language. It's much faster on our end to post stories if they are submitted in Markdown so we don't have to format them ourselves. 

**Describe the solution you'd like**
I'd like for there to be help text next to the Content text entry box on the Success Stories form indicating Markdown is preferred.

**Describe alternatives you've considered**
Currently we either reach out to request the submitter put their submission into Markdown after we receive it or we put it in Markdwown ourselves.

**Additional context**
Suggested text to add to [the Success Stories submission form](https://www.python.org/success-stories/create/) is:
"Submissions in Markdown are strongly preferred and can be processed more quickly" as shown in the attached screenshot in red. 
(I'm not 100% sure that wording is the accurate way to describe text being "in Markdown"; please edit if it doesn't quite make sense as I've written it. Thank you!)
![Screenshot of pythondotorg successs story form](https://github.com/python/pythondotorg/assets/93948470/62c35597-cd7b-4175-9e5f-4b5c5cba8159)

@ewdurbin

**Comment by JacobCoffee** [comment]
first glance: I believe this would be done in or around https://github.com/python/pythondotorg/blob/a3719ef6e673b6eb4ce9375dc7bd16a00286b8c7/successstories/forms.py#L9
