### ISSUE TITLE
404s on PSF >>> About

### ISSUE THREAD

**Issue by omerfkeles** [proevo/pythondotorg#2366]
**Describe the bug**
When visiting the Python Software Foundation's "About" page, there are a few broken links (five in total).

**To Reproduce**
1. Go to https://www.python.org/psf/about/.
2. Scroll down to the "Community" header.
3. Click on the embedded links within the first three bullet points:
- We host [PyCon US](https://www.python.org/psf/about/us.pycon.org)...
- We [give grants](https://www.python.org/psf/about/python.org/psf/grants) to groups...
- We are responsible for establishing, maintaining, and enforcing the [Python Code of Conduct](https://www.python.org/psf/about/python.org/codeofconduct)...
4. Scroll down to the "Investing in Python & Tools" header.
5. Click on the embedded links in the first bullet point and bottom right corner cell of the table:
- We host [PyPI](https://www.python.org/psf/about/pypi.org)...
> [PYCON US](https://www.python.org/psf/about/us.pycon.org)
6. Each link that is clicked on is a 404 page.

**Expected behavior**
Under "Community" header:
- [PyCon US](us.pycon.org)
- [give grants](python.org/psf/grants)
- [Python Code of Conduct](python.org/codeofconduct)

Under "Investing in Python & Tools" header:
- [PyPI](pypi.org)
> [PYCON US](us.pycon.org)

**Desktop (please complete the following information):**
 - Browser: all

**Additional context**
All of the broken links mentioned above work fine when adjusting `https://www.python.org/psf/about/[relevant URL]` to `[relevant URL]`.

**Comment by hugovk** [comment]
This should be fixed now. They were mostly missing the `https://` prefix. 

I also updated "12 Python-related community groups, conferences, and projects" to 20.

@omerfkeles Thanks for the report, if there's nothing else, please could you close this issue now?
