### ISSUE TITLE
Update podcasts on A/V page 

### ISSUE THREAD

**Issue by hugovk** [proevo/pythondotorg#2368]
**Is your feature request related to a problem? Please describe.**

Update the list of podcasts at https://www.python.org/doc/av/ 

**Describe the solution you'd like**

Move Podcast.\_\_init\_\_ to the inactive list. 

Add these to the active list:

- https://podcasters.spotify.com/pod/show/corepy
- https://pythonbytes.fm/
- https://podcast.pythontest.com/
- https://pythonpeople.fm/
- https://pythoncommunitynews.transistor.fm/
- https://djangochat.com/
- https://www.pybitespodcast.com/
- https://podcasters.spotify.com/pod/show/sad-python-girls-club

**Describe alternatives you've considered**
No changes, or find another page to link to that can list these. 

**Additional context**

Brought up at https://github.com/python/editorial-board/issues/1.

**Comment by JacobCoffee** [comment]
This seems to require database access as its not defined anywhere that I can find :)

**Comment by hugovk** [comment]
I have access now so have updated the list, except put [Python Community News](https://pythoncommunitynews.transistor.fm/) under inactive because the last one was Feb 2023. I also added PyCon US and EuroPython to the videos list.

https://www.python.org/doc/av/

**Comment by Mariatta** [comment]
Hi, would you all mind adding the PyPodcats podcast series to the active podcast list?

PyPodcats:Hidden Figures of Python podcast series.  Our goal is to highlight the contributions and accomplishments of the underrepresented group members in the Python community.

URL https://pypodcats.live

**Comment by hugovk** [comment]
Added! And thank you for PyPodcats!
