### ISSUE TITLE
Downloads API (v2) should return release cycle status

### ISSUE THREAD

**Issue by not7cd** [proevo/pythondotorg#2386]
**Is your feature request related to a problem? Please describe.**
I want to use release API endpoint in Renovate for automated updates.
It in turn need to know if a release is deprecated (end-of-life) or LTS (not sure how this translates to Python versioning)
These are not required, but would be a helpful addition.

**Describe the solution you'd like**
Data in https://github.com/python/devguide/blob/main/include/release-cycle.json  
Added to each release in https://www.python.org/api/v2/downloads/release/

Or release-cycle.json as a new endpoint. 

**Describe alternatives you've considered**
A file in devguide can be parsed by Renovate and then merged to API output, but this seems fragile.
https://github.com/python/devguide/blob/main/include/release-cycle.json

**Additional context**
https://github.com/renovatebot/renovate/discussions/27581

**Comment by hugovk** [comment]
> or LTS (not sure how this translates to Python versioning)

Python doesn't have LTS releases, they're all supported for 5 years.

---


You may find the third-party https://endoflife.date/python useful, it has an endpoint at https://endoflife.date/api/python.json. See also https://endoflife.date/docs/api

You can see if a release is EOL, or still under bugfix or security support.

There's also some GitHub Actions using it:

https://github.com/endoflife-date/endoflife.date/wiki/Known-Users
