### ISSUE TITLE
Get data from PostgreSQL Database from table with : in name

### ISSUE THREAD

**Issue by Oleg-Savinkov** [proevo/pythondotorg#2427]
Hello! I'm a beginner in Python. I'm trying to get data from a PostgreSQL database. Here is a query in Python 

`postgreSQL_select_Query = 'select * from ''abbott:Account" limit 100 ' `

I note that the table is called "abbott:Account", and I get the data with this particular request from DBeaver, everything is fine. But in Python I get a syntax error related to :. I could not solve the problem by any means. Tell me, how can I generate such a query in Python?

**Comment by hugovk** [comment]
This is the issue tracker for the actual website at https://www.python.org/.

You're better off asking at one of these places:

* https://discuss.python.org/c/users/7
* https://www.pythondiscord.com/
* https://stackoverflow.com/questions/tagged/python

**Comment by Oleg-Savinkov** [comment]
Thanks! Sorry!

**Comment by hugovk** [comment]
Please will you also close this issue? Thank you!

**Comment by Oleg-Savinkov** [comment]
The question has been moved to another branch
