### ISSUE TITLE
Conflicting maintenance status listed for 3.11

### ISSUE THREAD

**Issue by zfortier** [proevo/pythondotorg#2429]
This page shows 3.11 as currently accepting bug fixes: https://www.python.org/downloads/

However this page indicates (in 2 places) that 3.11 is only accepting security fixes: https://devguide.python.org/versions/

I suspect the dev guide was updated by somebody with specific knowledge that no additional bug fix releases are planned, but that should be reflected on the downloads page as well. One page should be updated to reflect the actual current maintenance status of 3.11.

**Comment by hugovk** [comment]
Python 3.11 is only accepting security fixes. 

The devguide was recently updated and is correct, see also PEP 664:

https://peps.python.org/pep-0664/

@pablogsal Please could you update the downloads page?

**Comment by ned-deily** [comment]
Thanks for the report. The downloads page has been updated to show 3.11's maintenance status as `security`.
