### ISSUE TITLE
Error in _init_.py code

### ISSUE THREAD

**Issue by trueblues2024** [proevo/pythondotorg#2438]
I tried to install scapy library using (python -m pip install scapy)
It showed me Error at _init_.py line 2348 and 2349
So the library is not installed, I opened the _init_.py from (C:\Users\lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\_init_.py)
Then I moved to line 2348 and 2349 and replaced **"ImpImporter" by "zipimporter"**
after then I tried to install the library using python -m pip install scapy
It is success so community please replace that in python latest versions.
 

I have attached the image of that please replace "ImpImporter" by "zipimporter"
![bug1](https://github.com/python/pythondotorg/assets/167015753/08d63165-d565-4078-829b-e1d8f7612c59)

**Comment by Mariatta** [comment]
This issue tracker is for Python.org website and not for general issues about Python. You'll probably get some answers about this behavior on StackOverflow
