### ISSUE TITLE
Please update "Python for AIX" info under the Downloads for Other Platforms page. 

### ISSUE THREAD

**Issue by ayappanec** [proevo/pythondotorg#2445]
"Python for AIX" section under the Downloads for Other Platforms page points to aixtools.net site. That site is no more maintained now. Up to date AIX binary packages for Python is provided through IBM AIX Toolbox site for the last 7-8 years and we (IBM AIX Toolbox team) are very much committed to do that well into the future. 
The request here is to update the section with below contents.

" AIX binary packages for Python are available from [IBM AIX Toolbox](https://www.ibm.com/support/pages/aix-toolbox-open-source-software-downloads-alpha) in RPM form. They can be installed using dnf package manager. Visit [Get Started](https://www.ibm.com/support/pages/aix-toolbox-open-source-software-get-started) page for more details. "

**Comment by JacobCoffee** [comment]
This has been updated @ayappanec, thanks for helping keep the links up to date!

![image](https://github.com/user-attachments/assets/47328f13-ba3b-46cc-987f-aba534337474)

**Comment by ayappanec** [comment]
Thanks for the support.
