### ISSUE TITLE
添加多语言（Add more language）

### ISSUE THREAD

**Issue by Age10-Moyu** [proevo/pythondotorg#2449]
英文，看不懂一点.jpg
（I can't read English =A=）
---
_（Although I use machine translation, it can only be like this, after all, my English is terrible, so I will leave it at that......）_ 
_（有没有中国同胞？顶一下！）_

**Comment by hugovk** [comment]
If you're looking for Chinese translations of the language  documentation, please see:

* https://docs.python.org/zh-cn/3/
* https://docs.python.org/zh-tw/3/

**Comment by Age10-Moyu** [comment]
我的意思是，能不能把Shell添加多语言

**Comment by aisk** [comment]
What do you mean by "shell"?

**Comment by Age10-Moyu** [comment]
> What do you mean "shell"?
就是“Python IDLE Shell”的意思_（That's what "Python IDLE Shell" means）_

**Comment by JacobCoffee** [comment]
If this is for the shell you use locally, check CPython https://github.com/python/cpython/.

For the shell we have on python.org i dont think we can do this, but if you find something in the docs of https://www.pythonanywhere.com/ let me know and feel free to re-open.
