### ISSUE TITLE
Python 3.12 docs website search results prioritizes "what's new" instead of actual topic

### ISSUE THREAD

**Issue by Saba-Sabato** [proevo/pythondotorg#2452]
**Describe the bug**
Searching for library modules on 3.12 returns first a list of "What's new in \<version\>" pages instead of the searched for module.

**To Reproduce**
1. Go to https://docs.python.org/3.12/index.html
2. Click on search box in top right corner, enter e.g. "asyncio" and hit enter
3. [Scroll through results](https://docs.python.org/3.12/search.html?q=asyncio)
4. See that the first result is "History and License" followed by 10 (!) "What’s New In Python \<version\>" results. The 11th result is the actual asyncio module.

**Expected behavior**
I would expect the asyncio module page to be the first result, or at the very least to appear very close to the top. This has been the case in previous versions of the website search.

**Screenshots**
(the list goes on a few more entries below the screenshot)
<img width="880" alt="image" src="https://github.com/python/pythondotorg/assets/20134422/43c44cd9-39f1-49ac-9800-ec59fe182245">

Compare with search from 3.11:
<img width="1118" alt="image" src="https://github.com/python/pythondotorg/assets/20134422/8e07f1c8-151d-4ea3-86c6-bc5454194399">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 123

**Additional context**
This happens for other topics too, not only modules.

**Comment by Mariatta** [comment]
I think this is an issue with Sphinx search feature and not Python issue.

**Comment by Saba-Sabato** [comment]
> I think this is an issue with Sphinx search feature and not Python issue.

Ah, you're right! Was a bit tricky to find where to post this issue. Thanks! I think this can be closed.

**Comment by Mariatta** [comment]
Closing since it is not relevant.
