### ISSUE TITLE
Links on psfmember.org mislabelled

### ISSUE THREAD

**Issue by toonarmycaptain** [proevo/pythondotorg#2478]
**Describe the bug**
Links on psfmember.org website when logged in are all labelled with \<username\>

**To Reproduce**
1. Go to psfmember.org
2. Login
3. Look at links in header and footer
4. Observe that the visual text is \<username\> 3x

**Expected behavior**
Links should be labelled user-info, logout, etc

**Screenshots**

![image](https://github.com/python/pythondotorg/assets/29956894/a7c10e28-6b0b-476e-bcdb-05172459e502)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Firefox
 - Version 127.0.2

**Additional context**
If there is a repo for psfmember.org, please redirect this issue; making that repo discoverable (preferably on the website itself) and linking or displaying where to get help/send bugs for that site would also be useful.

**Comment by JacobCoffee** [comment]
psfmember.org is its own service with no public repository. 
@indepndnt could you investigate if you have access or should I follow up with the site maintainers? This still does occur.

**Comment by indepndnt** [comment]
@JacobCoffee Can we confirm that this still occurs? I'm not seeing it today:

![image](https://github.com/user-attachments/assets/ce0c42d2-fdc4-4482-bd10-fcba0d45d125)

**Comment by JacobCoffee** [comment]
Im not able to see it any more either 🤔 @indepndnt
