### ISSUE TITLE
Community IRC page links to deactivated Zulip organization

### ISSUE THREAD

**Issue by shenanigansd** [proevo/pythondotorg#2488]
The Python Zulip instance has been deactivated:
https://discuss.python.org/t/should-we-continue-using-zulip/2816
https://discuss.python.org/t/notice-python-zulip-instance-shutdown-imminent/23917

However, https://www.python.org/community/irc/ still links to https://python.zulipchat.com/, and we (https://discord.gg/python) have recently had someone come asking about why it was deactivated.

Since the community no longer exists, the references on this site should be removed.

**Comment by hugovk** [comment]
Thanks, I've removed this chunk from https://www.python.org/community/irc/:

```rst
As an unofficial alternative to IRC, you can use `the Zulip livechat about Python`_. It works in your browser and you can create a free login to view and post messages. In particular, the `#general/help`_ "stream" (or channel) is a place to ask for and give help with general Python usage. 

.. _the Zulip livechat about Python: https://python.zulipchat.com/
.. _#general/help: https://python.zulipchat.com/#narrow/stream/174027-general.2Fhelp
```

**Comment by Mariatta** [comment]
Thanks @hugovk for fixing and thanks @shenanigansd for raising this issue. I confirmed that the page has been updated.
