### ISSUE TITLE
Government United States of America

### ISSUE THREAD

**Issue by david1234121** [proevo/pythondotorg#2490]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hugovk** [comment]
@david1234121 Please don't spam, this is the second time this week: https://github.com/python/pythondotorg/issues/2489

**Comment by ezio-melotti** [comment]
@python/organization-owners, more spam for you :tada:
