### ISSUE TITLE
Please update "Python for OS/390 and z/OS" in the Download page

### ISSUE THREAD

**Issue by jcy-zaas** [proevo/pythondotorg#2494]
The [Download Python for Other Platforms | Python.org ](https://www.python.org/download/other/)webpage seems to indicate Rocket Software is the sole provider of Python for z/OS. IBM has made Open Enterprise SDK for Python available for the z/OS platform since 2021 with the 3.10 release and we are following the community release closely ever since. I am the product manger for IBM Open Enterprise SDK for Python, and would like to get this information updated on the webpage? Please let me know who I should work with regarding this.

**Comment by Mariatta** [comment]
Do you have a suggested text copy we should use on the page?

We'll need to ping someone with CMS access (eg one of the PSF staff or Python Release Managers) to update the page. If you have the suggested text copy ahead of time, that would be helpful.

Thank you.

**Comment by jcy-zaas** [comment]
Here is my suggestion for the revision:

Python for z/OS is available from IBM for no license charge. It is available in PAX format from [Early Programs Web Tool](https://early-access.ibm.com/software/support/trial/cst/programwebsite.wss?siteId=1483&tabId=5523) or SMP/E format from [Shopz](https://www.ibm.com/software/shopzseries/ShopzSeries_public.wss). Optional no-cost Subscription and Support (S&S) is available in the Shopz ordering process.
Please visit [the IBM Open Enterprise SDK for Python product page](https://www.ibm.com/products/open-enterprise-python-zos) for more information.

**Comment by jcy-zaas** [comment]
I just posted my proposed text in GitHub
Python for z/OS is available from IBM for no license charge. It is available in PAX format from Early Programs Web Tool<https://early-access.ibm.com/software/support/trial/cst/programwebsite.wss?siteId=1483&tabId=5523> or SMP/E format in Shopz<https://www.ibm.com/software/shopzseries/ShopzSeries_public.wss>. Optional no-cost Subscription and Support (S&S) is available in the Shopz ordering process.
Please visit the IBM Open Enterprise SDK for Python product page<https://www.ibm.com/products/open-enterprise-python-zos> for more information.

Please note Rocket Software is using our Open Enterprise SDK for Python releases as well.

Thanks

Best Regards,
JC
J.C. Yao, Ph. D.
Principal Product Manager for C/C++, Python and Node.js
Compilation Technology and Enterprise Products
1 North Castle Drive, Armonk, NY 10504-1784
phone: +1-914-512-8296
email: ***@***.******@***.***>


From: Mariatta ***@***.***>
Date: Thursday, August 1, 2024 at 13:40
To: python/pythondotorg ***@***.***>
Cc: JC Yao ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [python/pythondotorg] Please update "Python for OS/390 and z/OS" in the Download page (Issue #2494)
Do you have a suggested text copy we should use on the page? We'll need to ping someone with CMS access (eg one of the PSF staff or Python Release Managers) to update the page. If you have the suggested text copy ahead of time, that would be


Do you have a suggested text copy we should use on the page?

We'll need to ping someone with CMS access (eg one of the PSF staff or Python Release Managers) to update the page. If you have the suggested text copy ahead of time, that would be helpful.

Thank you.

?

**Comment by ned-deily** [comment]
Thanks for the suggested wording. The web page has been updated.
