### ISSUE TITLE
Python 3.12.5 gzipped source tarball download 404s

### ISSUE THREAD

**Issue by edmorley** [proevo/pythondotorg#2499]
**Describe the bug**
The gzipped source tarball URL for the recent Python 3.12.5 release is 404ing:
https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tgz

**To Reproduce**
1. Visit https://www.python.org/downloads/release/python-3125/
2. Scroll down to "Files"
3. Click the "Gzipped source tarball" link (which targets https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tgz)

**Expected behavior**
Successful download of the file.

**Additional context**

The XZ file variant works fine - the issue only affects the gzipped version (which is the version used by our binary build automation). For example:

```
$ curl -I https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tgz
HTTP/2 404
server: nginx
content-type: text/html
x-clacks-overhead: GNU Terry Pratchett
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
age: 240
date: Wed, 07 Aug 2024 13:47:17 GMT
x-served-by: cache-lga21957-LGA, cache-lcy-eglc8600048-LCY
x-cache: HIT, HIT
x-cache-hits: 27, 0
x-timer: S1723038438.879842,VS0,VE1
strict-transport-security: max-age=63072000; includeSubDomains; preload
content-length: 146
```

```
$ curl -I https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tar.xz
HTTP/2 200
server: nginx
content-type: application/octet-stream
last-modified: Tue, 06 Aug 2024 20:39:17 GMT
etag: "66b289f5-1379efc"
x-clacks-overhead: GNU Terry Pratchett
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
age: 3261
date: Wed, 07 Aug 2024 13:48:14 GMT
x-served-by: cache-lga21928-LGA, cache-lcy-eglc8600058-LCY
x-cache: MISS, HIT
x-cache-hits: 0, 0
x-timer: S1723038495.804345,VS0,VE1
strict-transport-security: max-age=63072000; includeSubDomains; preload
content-length: 20422396
```

**Comment by hugovk** [comment]
Thanks for the report, we're looking into it.

**Comment by JacobCoffee** [comment]
This should be resolved @edmorley

**Comment by edmorley** [comment]
Thank you - working for me now :-)
