### ISSUE TITLE
Please update "Python for OS/390 and z/OS" in the Download page

### ISSUE THREAD

**Issue by PWFlyMan** [proevo/pythondotorg#2503]
**Describe the bug**
On https://www.python.org/download/other/

**Change Request:** Please remove the text "They support both Python 2 and Python 3."
**Reason:** I work for Rocket Software and we support Python 3.7+, rather than update again in future just removing the version references is the best option.

**Change Request:** Change sub-heading "Python for OS/390 and z/OS" to "Python for z/OS"
**Reason:** OS/390 is very old and no longer under active support.

**To Reproduce**
1. Go to 'https://www.python.org/download/other/'
2. Scroll down to '....'
4. Until you see "Python for OS/390 and z/OS"

**Comment by hugovk** [comment]
Thanks, I've updated this.

**Comment by hugovk** [comment]
@PWFlyMan Please can you close this issue now?

**Comment by PWFlyMan** [comment]
Thank you.
