### ISSUE TITLE
The Help page refers to an old category on discuss.python.org

### ISSUE THREAD

**Issue by contrast-jproberts** [proevo/pythondotorg#2508]
**Describe the bug**
The Help page refers to an old category on discuss.python.org that doesn't exist anymore.

**To Reproduce**
1. Go to https://www.python.org/about/help/#got-a-python-problem-or-question
2. Click on the link in second item of the list ([Users category of the discuss.python.org website](https://discuss.python.org/c/users/))
3. See Page Not Found error

**Expected behavior**
I expected the link to resolve to a place in discuss.python.org for questions and answers. I think that would be https://discuss.python.org/c/help/ .

**Comment by hugovk** [comment]
Thanks for the report! This is now fixed.
