### ISSUE TITLE
Bug(sponsors): When creating a new sponsor app the first contact should default to the primary

### ISSUE THREAD

**Issue by JacobCoffee** [proevo/pythondotorg#2610]
### Describe the bug

New sponsors form fails due to missed checkbox

![image](https://github.com/user-attachments/assets/b196bd4b-4cdd-4133-acaa-0e3ab53cb8c2)

### To Reproduce

1. Create sponsorship application
2. Once you enter into, submit
3. Be met with angry form invalidation: 
![image](https://github.com/user-attachments/assets/5d9c1d55-c2b2-46d5-b73e-bab801711ddb)

### Expected behavior

The first contact is usually going to be the primary. By defaulting this to checked we save some annoyance and headache for users having to reupload images because they forgot to click the box.

### URL to the issue

https://github.com/python/pythondotorg/blob/096ac337e1ccef8b2659699885a60b9c71d7fbd7/sponsors/models/sponsors.py#L154

### Browsers

Other

### Operating System

Other

**Comment by SDprogramer** [comment]
Is this issue still open or it is fixed by other members please tell. If not then i want to fix it. I will tell the approach clearly.
