### ISSUE TITLE
Bug: Link to New Deprecations is broken

### ISSUE THREAD

**Issue by Mariatta** [proevo/pythondotorg#2616]
### Describe the bug

In https://www.python.org/downloads/release/python-3130rc2/, under "Deprecations & Removals" heading, the link to new deprecations link to
- https://docs.python.org/3.13/whatsnew/3.13.html#deprecated

This link doesn't work. It should link to:
- https://docs.python.org/3.13/whatsnew/3.13.html#new-deprecations

<img width="678" alt="Screenshot 2024-09-27 at 4 56 08 PM" src="https://github.com/user-attachments/assets/0d2a284f-07ea-4cd8-9c03-d1ad4762b57c">

### To Reproduce

1. Go to https://www.python.org/downloads/release/python-3130rc2/
2. Click the "New Deprecations" link
3. It shows the top of "What's New" page

### Expected behavior

It should take the user to the heading for "New Deprecations" in the "What's New" page.

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Browsers

Chrome

### Operating System

macOS

### Browser Version

Version 129.0.6668.60 (Official Build) (arm64)

**Comment by hugovk** [comment]
Thanks for the report, this is now fixed.
