### ISSUE TITLE
Bug: Download directs to version 3.12.6 insted of 3.12.7

### ISSUE THREAD

**Issue by MarceloBergweiler** [proevo/pythondotorg#2634]
### Describe the bug

The download link "Latest" directs to the old version 3.12.6 instead of 3.12.7, already released 01 OCT 2024.

### To Reproduce

1. Go to "https://www.python.org/". The "Download" section still points to the older version 3.12.6.

### Expected behavior

The download link "Latest" should direct to version 3.12.7.

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Browsers

Firefox

### Operating System

Windows

**Comment by hugovk** [comment]
Thanks for the report, closing in favour of https://github.com/python/pythondotorg/issues/2635 which has a screenshot.
