### ISSUE TITLE
Bug: Main Page Still Has a Reference to 3.12.6 as Latest Version

### ISSUE THREAD

**Issue by questionlp** [proevo/pythondotorg#2635]
### Describe the bug

Issue #2631 was partially resolved in that the latest Python version listed in the **Downloads** navigation dropdown is now listing the correct version, but the **Downloads** block below the navigation and header is still listing 3.12.6 instead of 3.12.7.

### To Reproduce

Downloads Latest

1. Open a web browser
2. Browse to <https://www.python.org>
3. Scroll down to the **Get Started** and **Downloads** blocks, Latests lists the previous version

### Expected behavior

3.12.7 should be listed as the latest version and should link to the appropriate [release page](https://www.python.org/downloads/release/python-3127/).

### URL to the issue

https://www.python.org/

### Screenshots

![Screenshot_20241004_105641](https://github.com/user-attachments/assets/abb6a2c3-0340-4692-9192-9757081f2dd0)

### Browsers

Firefox, Chrome

### Operating System

Linux

### Browser Version

130

**Comment by ygale** [comment]
As seen in `/downloads/factories.py`, this comes from an API call to `GET https://www.python.org/api/v2/downloads/release/`. And if you call that endpoint, it indeed shows 3.12.7 as the latest version. So I think all we need here is a site restart.

**Comment by ned-deily** [comment]
And it should now show 3.13.0!

**Comment by questionlp** [comment]
Happy 3.13.0 release day!

**Comment by ewdurbin** [comment]
Digging into this and the previous issue I discovered the underlying bug causing these updates to be delayed. #2638 should make all of this much smoother for releases after it is merged.

**Comment by JacobCoffee** [comment]
#2638 did fix it seems :)
