### ISSUE TITLE
Python next  Release date: XXXX-XX-XX on changelog of released python

### ISSUE THREAD

**Issue by ZeeD** [proevo/pythondotorg#2642]
### Describe the bug

While on https://docs.python.org/3.11/whatsnew/changelog.html#python-3-11-10-final and previous version the changelog correctly show the latest version and release date, on https://docs.python.org/3.12/whatsnew/changelog.html#python-next and https://docs.python.org/3.13/whatsnew/changelog.html#python-next there is just the text 

Python next

Release date: XXXX-XX-XX

the information should be updated

### To Reproduce

go to https://docs.python.org/3.12/whatsnew/changelog.html and https://docs.python.org/3.13/whatsnew/changelog.html

### Expected behavior

You should see something like

Python 3.12.7

Release date: 2024-10-01

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Browsers

Firefox

### Operating System

Windows

**Comment by hugovk** [comment]
This is a placeholder for the _next_ release, which hasn't happened yet. It will be filled in when the next release takes place. After that, there'll be another "next" and "XXXX-XX-XX".
