### ISSUE TITLE
Bug: Broken relative link to the PEPs API on the PEP 0 page

### ISSUE THREAD

**Issue by nibley** [proevo/pythondotorg#2643]
### Describe the bug

On [the page for PEP 0](https://peps.python.org/pep-0000/), under the heading `API`, there is a broken link reading `PEPS API`.

Its HTML is `<a class="reference external" href="api/peps.json">PEPS API</a>` which produces the broken link [https://peps.python.org/pep-0000/api/peps.json](https://peps.python.org/pep-0000/api/peps.json).

It seems like the fix is `<a class="reference external" href="https://peps.python.org/api/peps.json">PEPS API</a>`, like the working link near the top of [the PEPs API page](https://peps.python.org/api/).

### To Reproduce

1. Go to [https://peps.python.org/pep-0000/](https://peps.python.org/pep-0000/)
2. Click on the link reading `PEPS API` in the sentence `The PEPS API is a JSON file of metadata about all the published PEPs.`

### Expected behavior

The link should instead resolve to [https://peps.python.org/api/peps.json](https://peps.python.org/api/peps.json).

### URL to the issue

https://peps.python.org/pep-0000/

### Browsers

Chrome

### Operating System

Linux

### Browser Version

1.69.168 Chromium

**Comment by hugovk** [comment]
Thanks for the report.

The link works from https://peps.python.org/ but not from https://peps.python.org/pep-0000/

Looks like the problem is here: 

https://github.com/python/peps/blob/0057f884930d342c1fb207bf64a054d34e3d7bfc/pep_sphinx_extensions/pep_zero_generator/writer.py#L186

Changing that to an absolute link is probably easiest:

```diff
-                "The `PEPS API <api/peps.json>`__ is a JSON file of metadata about "
+                "The `PEPS API </api/peps.json>`__ is a JSON file of metadata about "
```

Would you like to open a PR?

**Comment by nibley** [comment]
thanks for your quick feedback: PR is [opened](https://github.com/python/peps/pull/4045)

**Comment by nibley** [comment]
closing as resolving [PR](https://github.com/python/peps/pull/4045) was merged on `python/peps`

**Comment by hugovk** [comment]
Thank you!
