### ISSUE TITLE
Investigate logs forwarding to Datadog after IaC conversion

### ISSUE THREAD

**Issue by JacobCoffee** [proevo/pythondotorg#2651]
something about our fastly configuration changed Oct 21 (when we moved to terraform handling) that caused _all_ logs to go to datadog, not just the rate limit events.

is that something you could investigate?

[Slack Message](https://thepsf.slack.com/archives/G7MG5TXNX/p1730840056006569?thread_ts=1730839703.152459&cid=G7MG5TXNX)

**Comment by ewdurbin** [comment]
Should this transfer to https://github.com/python/pythondotorg/issues since the fastly config lives in the infra dir there?

**Comment by JacobCoffee** [comment]
Most obv. thing I can see between config months ago and now is the addition of this logging entry
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/95097324-6471-40a4-aaa0-4f0faec270f2">

**Comment by ewdurbin** [comment]
If I recall, that entry existed before but was limited to only when a rate limit event occurred... which I ostensibly what should be happening based on the config we have running right now... but all logs are going.
<img width="1000" alt="Screenshot 2024-11-05 at 4 21 48 PM" src="https://github.com/user-attachments/assets/d85eb765-c451-4b5b-91a2-4a18522883a7">
