### ISSUE TITLE
Bug: 403 Access denied

### ISSUE THREAD

**Issue by andrew-davey** [proevo/pythondotorg#2663]
### Describe the bug

Getting 403 access denied when trying to download any version of Python 

### To Reproduce

https://www.python.org/ftp/python/3.13.0/python-3.13.0-amd64.exe

### Expected behavior

Download should start

### URL to the issue

https://www.python.org/ftp/python/3.13.0/python-3.13.0-amd64.exe

### Browsers

Chrome, Microsoft Edge

### Operating System

Windows

**Comment by emerikaji** [comment]
I second this, none of the downloads for any platform are available.

**Comment by v3rsi0n** [comment]
Same issue for macOS

**Comment by rgbysgt** [comment]
This is across all files under `/ftp/python` subpath, at least two bug tickets have been logged. Let's let the team respond

**Comment by b001io** [comment]
Yep, same issue for me.

**Comment by UserInProgress** [comment]
Well I've been thinking why they might have blocked my access. Thank God I'm not the only one

**Comment by tjhorner** [comment]
Does anyone have a mirror that can be used in the meantime while the team fixes the issue? I can't find any that are reasonably up-to-date.

**Comment by rtaic-coder** [comment]
Same here.

**Comment by hanspayer** [comment]
Same here as well

**Comment by danieljaffe** [comment]
Same issue here as well.

**Comment by emerikaji** [comment]
> Does anyone have a mirror that can be used in the meantime while the team fixes the issue? I can't find any that are reasonably up-to-date.

I had to resort to getting a version 3.12.5 executable from LO4D. I don't think any other mirrors have a more up to date version, at least none I could find.

**Comment by b001io** [comment]
Just tried again, the issue seems to be fixed.
