### ISSUE TITLE
Bug: gzipped and tarball for 3.10.15 source code have incorrect permissions

### ISSUE THREAD

**Issue by itsmoosh** [proevo/pythondotorg#2664]
### Describe the bug

The download links for 3.10.15 source code both return a 403 forbidden error.

### To Reproduce

1. Go to https://www.python.org/downloads/release/python-31015/
2. Click either of the download source code links at the bottom of the page, which point to:
https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz
https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tar.xz

The same problem happens using wget:
wget https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tgz
wget https://www.python.org/ftp/python/3.10.15/Python-3.10.15.tar.xz

### Expected behavior

Navigating to the links above results in downloading the described compressed archive.

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Browsers

Chrome, Other

### Operating System

Linux

### Browser Version

130.0.6723.69

### Relevant log output

```shell
Connecting to www.python.org (www.python.org)|151.101.128.223|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-11-26 14:04:34 ERROR 403: Forbidden.
```

**Comment by rgbysgt** [comment]
This is across all files under `/ftp/python` subpath, not just 3.10... @hugovk  you're about to get a ton of tickets. I see already 2 have been logged

**Comment by hugovk** [comment]
Should be working now, thanks for the report. 

(re: https://github.com/python/pythondotorg/issues/2663, https://github.com/python/cpython/issues/127307)
